"""phase_25_client_session_version

Revision ID: 02ebe20f7dd7
Revises: d1e2f3a4b5c6
Create Date: 2026-06-07 00:43:33.116332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02ebe20f7dd7'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('athlete_cri_snapshots', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('clients', sa.Column('session_version', sa.Integer(), server_default='1', nullable=False, comment='Incrementado en logout-all para invalidar JWTs antiguos'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'session_version')
    op.alter_column('athlete_cri_snapshots', 'calculated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###
