"""add_dynamic_math_engine_models

Revision ID: 0ce5c397ea68
Revises: b0b47f01b18a
Create Date: 2026-03-06 17:14:05.929922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ce5c397ea68'
down_revision: Union[str, Sequence[str], None] = 'b0b47f01b18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_exercise_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('current_e1rm', sa.Float(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_athlete_stats_unique', 'athlete_exercise_stats', ['athlete_id', 'exercise_id'], unique=True)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('keys_p256dh', sa.String(length=255), nullable=False),
    sa.Column('keys_auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('actual_reps', sa.Integer(), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_sets_athlete_exercise_time', 'workout_sets', ['athlete_id', 'exercise_id', 'client_created_at'], unique=False)
    op.alter_column('tenants', 'subscription_tier',
               existing_type=postgresql.ENUM('FREE', 'PRO', name='subscriptiontier'),
               server_default='FREE',
               existing_nullable=False)
    op.alter_column('tenants', 'payment_provider',
               existing_type=postgresql.ENUM('MERCADO_PAGO', 'STRIPE', 'NONE', name='paymentprovider'),
               server_default='NONE',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'payment_provider',
               existing_type=postgresql.ENUM('MERCADO_PAGO', 'STRIPE', 'NONE', name='paymentprovider'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'subscription_tier',
               existing_type=postgresql.ENUM('FREE', 'PRO', name='subscriptiontier'),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_workout_sets_athlete_exercise_time', table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_athlete_stats_unique', table_name='athlete_exercise_stats')
    op.drop_table('athlete_exercise_stats')
    # ### end Alembic commands ###
