"""Add coach_id to training_archetypes

Revision ID: 1a8074ec92f2
Revises: 393ca789400e
Create Date: 2026-03-17 11:16:01.912715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8074ec92f2'
down_revision: Union[str, Sequence[str], None] = '393ca789400e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_archetypes', sa.Column('coach_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_training_archetypes_coach_id_users'), 'training_archetypes', 'users', ['coach_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_training_archetypes_coach_id_users'), 'training_archetypes', type_='foreignkey')
    op.drop_column('training_archetypes', 'coach_id')
    # ### end Alembic commands ###
