"""add_compound_indexes_for_dashboard_metrics

Revision ID: 1b275b188357
Revises: 49b5a4d918fb
Create Date: 2026-06-04 11:17:56.217773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b275b188357'
down_revision: Union[str, Sequence[str], None] = '49b5a4d918fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    
    # PASO 1: Agregar las columnas como Nullable primero para no romper las filas existentes
    op.add_column('financial_transactions', sa.Column('checkout_status', sa.String(length=20), nullable=True))
    op.add_column('financial_transactions', sa.Column('checkout_created_at', sa.DateTime(), nullable=True))
    op.add_column('financial_transactions', sa.Column('checkout_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('ff_checkout_v2', sa.Boolean(), server_default='false', nullable=False))
    
    # PASO 2: Ejecutar un Backfill de datos crudo en SQL para eliminar los NULLs
    op.execute(
        "UPDATE financial_transactions SET checkout_status = 'PENDING' WHERE checkout_status IS NULL"
    )
    op.execute(
        "UPDATE financial_transactions SET checkout_created_at = CURRENT_TIMESTAMP WHERE checkout_created_at IS NULL"
    )
    
    # PASO 3: Ahora que no existen NULLs, es seguro aplicar el alter_column con nullable=False
    op.alter_column('financial_transactions', 'checkout_status', nullable=False)
    op.alter_column('financial_transactions', 'checkout_created_at', nullable=False)

    # PASO 4: Inyección de los nuevos índices compuestos creados en Fase 6
    op.create_index('ix_clients_dashboard_metrics', 'clients', ['tenant_id', 'is_active', 'payment_status'], unique=False)
    op.create_index('ix_clients_dashboard_time', 'clients', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_fin_tx_dashboard', 'financial_transactions', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'ff_checkout_v2')
    op.drop_index('ix_fin_tx_dashboard', table_name='financial_transactions')
    op.drop_column('financial_transactions', 'checkout_confirmed_at')
    op.drop_column('financial_transactions', 'checkout_created_at')
    op.drop_column('financial_transactions', 'checkout_status')
    op.drop_index('ix_clients_dashboard_time', table_name='clients')
    op.drop_index('ix_clients_dashboard_metrics', table_name='clients')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professional_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ai_recommendation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('professional_decision', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('magnetic_locks_applied', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('computed_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    # ### end Alembic commands ###
