"""gamification_engine_models

Revision ID: 1b4cccf2f8f0
Revises: 6a69b73078d4
Create Date: 2026-03-06 19:05:10.262110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4cccf2f8f0'
down_revision: Union[str, Sequence[str], None] = '6a69b73078d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rewards_tenant_active', 'rewards', ['tenant_id', 'is_active'], unique=False)
    op.create_table('athlete_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index('ix_athlete_wallets_client', 'athlete_wallets', ['client_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['athlete_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_txs_created_at', 'wallet_transactions', ['created_at'], unique=False)
    op.create_index('ix_wallet_txs_wallet_type', 'wallet_transactions', ['wallet_id', 'transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wallet_txs_wallet_type', table_name='wallet_transactions')
    op.drop_index('ix_wallet_txs_created_at', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index('ix_athlete_wallets_client', table_name='athlete_wallets')
    op.drop_table('athlete_wallets')
    op.drop_index('ix_rewards_tenant_active', table_name='rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###
