"""Add plan drafts and analytics workload

Revision ID: 2ad4e4dc62eb
Revises: d3e4f5g6h7i8
Create Date: 2026-06-15 13:01:50.803522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ad4e4dc62eb'
down_revision: Union[str, Sequence[str], None] = 'd3e4f5g6h7i8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_churn_risk_scores'))
    )
    op.create_index(op.f('ix_churn_risk_scores_athlete_id'), 'churn_risk_scores', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_churn_risk_scores_calculated_at'), 'churn_risk_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_churn_risk_scores_id'), 'churn_risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_churn_risk_scores_tenant_id'), 'churn_risk_scores', ['tenant_id'], unique=False)
    op.create_table('coaching_intervention_triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('intervention_type', sa.String(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coaching_intervention_triggers'))
    )
    op.create_index(op.f('ix_coaching_intervention_triggers_athlete_id'), 'coaching_intervention_triggers', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_coaching_intervention_triggers_created_at'), 'coaching_intervention_triggers', ['created_at'], unique=False)
    op.create_index(op.f('ix_coaching_intervention_triggers_id'), 'coaching_intervention_triggers', ['id'], unique=False)
    op.create_index(op.f('ix_coaching_intervention_triggers_tenant_id'), 'coaching_intervention_triggers', ['tenant_id'], unique=False)
    op.create_table('scorecard_vault',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_event_id', sa.UUID(), nullable=False),
    sa.Column('last_client_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id', name=op.f('pk_scorecard_vault'))
    )
    op.create_index('ix_gaming_tenant_xp', 'scorecard_vault', ['tenant_id', 'total_xp'], unique=False, postgresql_using='btree')
    op.create_table('action_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('risk_score_id', sa.UUID(), nullable=True),
    sa.Column('intervention_trigger_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body_template', sa.String(), nullable=False),
    sa.Column('context_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'RESOLVED', 'IGNORED', name='actioncardstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_trigger_id'], ['coaching_intervention_triggers.id'], name=op.f('fk_action_cards_intervention_trigger_id_coaching_intervention_triggers')),
    sa.ForeignKeyConstraint(['risk_score_id'], ['churn_risk_scores.id'], name=op.f('fk_action_cards_risk_score_id_churn_risk_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_cards'))
    )
    op.create_index('idx_action_cards_tenant_pt_status', 'action_cards', ['tenant_id', 'professional_id', 'status'], unique=False)
    op.create_index(op.f('ix_action_cards_athlete_id'), 'action_cards', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_action_cards_id'), 'action_cards', ['id'], unique=False)
    op.create_index(op.f('ix_action_cards_professional_id'), 'action_cards', ['professional_id'], unique=False)
    op.create_index(op.f('ix_action_cards_status'), 'action_cards', ['status'], unique=False)
    op.create_index(op.f('ix_action_cards_tenant_id'), 'action_cards', ['tenant_id'], unique=False)
    op.create_table('plan_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=True),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], name=op.f('fk_plan_drafts_athlete_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_plan_drafts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name=op.f('fk_plan_drafts_trainer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_drafts'))
    )
    op.create_index('idx_plan_drafts_expires_at', 'plan_drafts', ['expires_at'], unique=False)
    op.create_table('scheduling_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scheduling_resources_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_resources'))
    )
    op.create_index(op.f('ix_scheduling_resources_tenant_id'), 'scheduling_resources', ['tenant_id'], unique=False)
    op.create_table('scheduling_class_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_capacity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['users.id'], name=op.f('fk_scheduling_class_sessions_professional_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['scheduling_resources.id'], name=op.f('fk_scheduling_class_sessions_resource_id_scheduling_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scheduling_class_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_class_sessions'))
    )
    op.create_index(op.f('ix_scheduling_class_sessions_professional_id'), 'scheduling_class_sessions', ['professional_id'], unique=False)
    op.create_index(op.f('ix_scheduling_class_sessions_resource_id'), 'scheduling_class_sessions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_scheduling_class_sessions_tenant_id'), 'scheduling_class_sessions', ['tenant_id'], unique=False)
    op.create_table('scheduling_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scheduling_class_sessions.id'], name=op.f('fk_scheduling_reservations_session_id_scheduling_class_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scheduling_reservations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_reservations'))
    )
    op.create_index(op.f('ix_scheduling_reservations_billing_reference_id'), 'scheduling_reservations', ['billing_reference_id'], unique=False)
    op.create_index(op.f('ix_scheduling_reservations_idempotency_key'), 'scheduling_reservations', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_scheduling_reservations_session_id'), 'scheduling_reservations', ['session_id'], unique=False)
    op.create_index(op.f('ix_scheduling_reservations_user_id'), 'scheduling_reservations', ['user_id'], unique=False)
    op.create_table('analytics_athlete_workload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('protocol_id', sa.UUID(), nullable=False),
    sa.Column('workload_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], name=op.f('fk_analytics_athlete_workload_athlete_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], name=op.f('fk_analytics_athlete_workload_protocol_id_protocols'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_analytics_athlete_workload_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_athlete_workload'))
    )
    op.create_index('idx_analytics_workload_athlete', 'analytics_athlete_workload', ['athlete_id'], unique=False)
    op.drop_index(op.f('ix_squad_notif_squad_created'), table_name='squad_notifications')
    op.create_index('ix_squad_notif_squad_created', 'squad_notifications', ['squad_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_squad_notif_squad_created', table_name='squad_notifications', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_squad_notif_squad_created'), 'squad_notifications', ['squad_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_index('idx_analytics_workload_athlete', table_name='analytics_athlete_workload')
    op.drop_table('analytics_athlete_workload')
    op.drop_index(op.f('ix_scheduling_reservations_user_id'), table_name='scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_reservations_session_id'), table_name='scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_reservations_idempotency_key'), table_name='scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_reservations_billing_reference_id'), table_name='scheduling_reservations')
    op.drop_table('scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_class_sessions_tenant_id'), table_name='scheduling_class_sessions')
    op.drop_index(op.f('ix_scheduling_class_sessions_resource_id'), table_name='scheduling_class_sessions')
    op.drop_index(op.f('ix_scheduling_class_sessions_professional_id'), table_name='scheduling_class_sessions')
    op.drop_table('scheduling_class_sessions')
    op.drop_index(op.f('ix_scheduling_resources_tenant_id'), table_name='scheduling_resources')
    op.drop_table('scheduling_resources')
    op.drop_index('idx_plan_drafts_expires_at', table_name='plan_drafts')
    op.drop_table('plan_drafts')
    op.drop_index(op.f('ix_action_cards_tenant_id'), table_name='action_cards')
    op.drop_index(op.f('ix_action_cards_status'), table_name='action_cards')
    op.drop_index(op.f('ix_action_cards_professional_id'), table_name='action_cards')
    op.drop_index(op.f('ix_action_cards_id'), table_name='action_cards')
    op.drop_index(op.f('ix_action_cards_athlete_id'), table_name='action_cards')
    op.drop_index('idx_action_cards_tenant_pt_status', table_name='action_cards')
    op.drop_table('action_cards')
    op.drop_index('ix_gaming_tenant_xp', table_name='scorecard_vault', postgresql_using='btree')
    op.drop_table('scorecard_vault')
    op.drop_index(op.f('ix_coaching_intervention_triggers_tenant_id'), table_name='coaching_intervention_triggers')
    op.drop_index(op.f('ix_coaching_intervention_triggers_id'), table_name='coaching_intervention_triggers')
    op.drop_index(op.f('ix_coaching_intervention_triggers_created_at'), table_name='coaching_intervention_triggers')
    op.drop_index(op.f('ix_coaching_intervention_triggers_athlete_id'), table_name='coaching_intervention_triggers')
    op.drop_table('coaching_intervention_triggers')
    op.drop_index(op.f('ix_churn_risk_scores_tenant_id'), table_name='churn_risk_scores')
    op.drop_index(op.f('ix_churn_risk_scores_id'), table_name='churn_risk_scores')
    op.drop_index(op.f('ix_churn_risk_scores_calculated_at'), table_name='churn_risk_scores')
    op.drop_index(op.f('ix_churn_risk_scores_athlete_id'), table_name='churn_risk_scores')
    op.drop_table('churn_risk_scores')
    # ### end Alembic commands ###
