"""Add compute units

Revision ID: 2f45f365cf9b
Revises: 46e8f853b687
Create Date: 2026-03-06 01:54:02.993495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f45f365cf9b'
down_revision: Union[str, Sequence[str], None] = '46e8f853b687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('compute_units_balance', sa.BigInteger(), server_default='500000', nullable=False))
    op.drop_column('tenants', 'ai_messages_used')
    op.drop_column('tenants', 'ai_messages_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('ai_messages_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('ai_messages_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'compute_units_balance')
    # ### end Alembic commands ###
