"""Add idempotency_key to WorkoutSets

Revision ID: 324cb07e1564
Revises: b1c4240da065
Create Date: 2026-06-05 12:59:00.248870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324cb07e1564'
down_revision: Union[str, Sequence[str], None] = 'b1c4240da065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('idempotency_key', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_workout_sets_client_created_at'), 'workout_sets', ['client_created_at'], unique=False)
    op.create_index(op.f('ix_workout_sets_idempotency_key'), 'workout_sets', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_sets_idempotency_key'), table_name='workout_sets')
    op.drop_index(op.f('ix_workout_sets_client_created_at'), table_name='workout_sets')
    op.drop_column('workout_sets', 'idempotency_key')
    # ### end Alembic commands ###
