"""Add TrainingArchetype

Revision ID: 393ca789400e
Revises: 9a09ad0040b5
Create Date: 2026-03-17 11:05:31.442876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '393ca789400e'
down_revision: Union[str, Sequence[str], None] = '9a09ad0040b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_archetypes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('days_per_week_min', sa.Integer(), nullable=False),
    sa.Column('days_per_week_max', sa.Integer(), nullable=False),
    sa.Column('exp_level_min', sa.Integer(), nullable=False),
    sa.Column('exp_level_max', sa.Integer(), nullable=False),
    sa.Column('primary_goal', sa.String(length=255), nullable=False),
    sa.Column('psychographic_profile', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_archetypes'))
    )
    op.drop_table('archetypes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetypes',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('nombre_comercial', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dias_por_semana', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('nivel_experiencia_requerido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('objetivo_principal', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('perfil_psicografico', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('archetypes_pkey'))
    )
    op.drop_table('training_archetypes')
    # ### end Alembic commands ###
