"""Add delivery_status

Revision ID: 39eb4dbe8bd3
Revises: 05a7e808c862
Create Date: 2026-03-02 01:03:50.940689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39eb4dbe8bd3'
down_revision: Union[str, Sequence[str], None] = '05a7e808c862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('delivery_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_plans', 'delivery_status')
    # ### end Alembic commands ###
