"""Add CompassionWallet and Legacy models

Revision ID: 40d31a8d132f
Revises: a242a87c0bfa
Create Date: 2026-05-28 20:47:42.075890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d31a8d132f'
down_revision: Union[str, Sequence[str], None] = 'a242a87c0bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_compassion_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('available_streak_freezes', sa.Integer(), nullable=False),
    sa.Column('recovery_tokens_balance', sa.Integer(), nullable=False),
    sa.Column('hibernation_status', sa.Boolean(), nullable=False),
    sa.Column('fatigue_index', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_athlete_compassion_wallets_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_compassion_wallets')),
    sa.UniqueConstraint('client_id', name=op.f('uq_athlete_compassion_wallets_client_id'))
    )
    op.create_index('ix_compassion_wallets_client', 'athlete_compassion_wallets', ['client_id'], unique=False)
    op.create_table('athlete_legacy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('current_legacy_level', sa.Integer(), nullable=False),
    sa.Column('total_consistency_gems', sa.Integer(), nullable=False),
    sa.Column('days_active_metabolism', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_athlete_legacy_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_athlete_legacy')),
    sa.UniqueConstraint('client_id', name=op.f('uq_athlete_legacy_client_id'))
    )
    op.create_index('ix_athlete_legacy_client', 'athlete_legacy', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_athlete_legacy_client', table_name='athlete_legacy')
    op.drop_table('athlete_legacy')
    op.drop_index('ix_compassion_wallets_client', table_name='athlete_compassion_wallets')
    op.drop_table('athlete_compassion_wallets')
    # ### end Alembic commands ###
