"""Add Command Center semaphore fields to Patient

Revision ID: 4656acfff03c
Revises: afc7b2953245
Create Date: 2026-06-29 12:28:37.164995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4656acfff03c'
down_revision: Union[str, Sequence[str], None] = 'afc7b2953245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mesocycles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mesocycles', 'routine_structure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estructura serializada de la rutina (Data Stripped)',
               existing_nullable=False)
    op.alter_column('mesocycles', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('mesocycles', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_mesocycles_coach_active'), table_name='mesocycles')
    op.drop_index(op.f('idx_mesocycles_routine_gin'), table_name='mesocycles', postgresql_using='gin')
    op.drop_index(op.f('idx_mesocycles_tenant_client'), table_name='mesocycles')
    op.create_index('idx_mesocycles_coach_active_models', 'mesocycles', ['coach_id', 'is_active'], unique=False)
    op.create_index('idx_mesocycles_tenant_client_models', 'mesocycles', ['tenant_id', 'client_id'], unique=False)
    op.add_column('patients', sa.Column('semaphore_status', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('primary_risk_factor', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('context_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('patients', sa.Column('last_risk_evaluation', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('snooze_until', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_squad_notif_squad_created'), table_name='squad_notifications')
    op.create_index('ix_squad_notif_squad_created', 'squad_notifications', ['squad_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.alter_column('video_reviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('video_reviews', 'ai_priority',
               existing_type=sa.VARCHAR(length=10),
               comment='P1, P2, P3',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_reviews', 'ai_priority',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='P1, P2, P3',
               existing_nullable=True)
    op.alter_column('video_reviews', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_squad_notif_squad_created', table_name='squad_notifications', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_squad_notif_squad_created'), 'squad_notifications', ['squad_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_column('patients', 'snooze_until')
    op.drop_column('patients', 'last_risk_evaluation')
    op.drop_column('patients', 'context_metadata')
    op.drop_column('patients', 'primary_risk_factor')
    op.drop_column('patients', 'semaphore_status')
    op.drop_index('idx_mesocycles_tenant_client_models', table_name='mesocycles')
    op.drop_index('idx_mesocycles_coach_active_models', table_name='mesocycles')
    op.create_index(op.f('idx_mesocycles_tenant_client'), 'mesocycles', ['tenant_id', 'client_id'], unique=False)
    op.create_index(op.f('idx_mesocycles_routine_gin'), 'mesocycles', ['routine_structure'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_mesocycles_coach_active'), 'mesocycles', ['coach_id', 'is_active'], unique=False)
    op.alter_column('mesocycles', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('mesocycles', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('mesocycles', 'routine_structure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Estructura serializada de la rutina (Data Stripped)',
               existing_nullable=False)
    op.alter_column('mesocycles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    # ### end Alembic commands ###
