"""add payment_status to tenant

Revision ID: 4b0dd3c73e27
Revises: a236445d5e37
Create Date: 2026-03-07 01:53:37.932721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0dd3c73e27'
down_revision: Union[str, Sequence[str], None] = 'a236445d5e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('payment_status', sa.String(length=50), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'payment_status')
    # ### end Alembic commands ###
