"""add_subscription_monetization

Revision ID: 5b127a409e56
Revises: 66908013165a
Create Date: 2026-03-06 12:13:09.206112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b127a409e56'
down_revision: Union[str, Sequence[str], None] = '66908013165a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type explicitly for Postgres
    sa.Enum('FREE', 'PRO', name='subscriptiontier').create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', name='subscriptiontier'), server_default='FREE', nullable=False))
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('subscription_status', sa.String(length=50), server_default='active', nullable=False))
    op.alter_column('tenants', 'referral_reward_claimed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'referral_reward_claimed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('tenants', 'subscription_status')
    op.drop_column('tenants', 'stripe_subscription_id')
    op.drop_column('tenants', 'subscription_tier')
    # ### end Alembic commands ###
    
    # Drop enum type explicitly
    sa.Enum('FREE', 'PRO', name='subscriptiontier').drop(op.get_bind())
