"""add_viral_engine_fields

Revision ID: 66908013165a
Revises: 8e7ea5c1c527
Create Date: 2026-03-06 11:45:05.478871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66908013165a'
down_revision: Union[str, Sequence[str], None] = '8e7ea5c1c527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('referred_by_tenant_id', sa.UUID(), nullable=True))
    op.add_column('tenants', sa.Column('referral_reward_claimed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('tenants', 'primary_color',
               existing_type=sa.VARCHAR(length=7),
               server_default=None,
               existing_nullable=False)
    op.create_foreign_key(None, 'tenants', 'tenants', ['referred_by_tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.alter_column('tenants', 'primary_color',
               existing_type=sa.VARCHAR(length=7),
               server_default=sa.text("'#CEFF00'::character varying"),
               existing_nullable=False)
    op.drop_column('tenants', 'referral_reward_claimed')
    op.drop_column('tenants', 'referred_by_tenant_id')
    op.drop_column('tenants', 'stripe_customer_id')
    # ### end Alembic commands ###
