"""cascade_builder_master_templates

Revision ID: 7e57461249dc
Revises: 0ce5c397ea68
Create Date: 2026-03-06 17:36:08.489895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e57461249dc'
down_revision: Union[str, Sequence[str], None] = '0ce5c397ea68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_plans', sa.Column('is_master', sa.Boolean(), nullable=False))
    op.add_column('workout_plans', sa.Column('derived_from_master_id', sa.UUID(), nullable=True))
    op.alter_column('workout_plans', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'workout_plans', 'workout_plans', ['derived_from_master_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_plans', type_='foreignkey')
    op.alter_column('workout_plans', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('workout_plans', 'derived_from_master_id')
    op.drop_column('workout_plans', 'is_master')
    # ### end Alembic commands ###
