"""Sprint 1 NutritionPlan JSONB

Revision ID: 86dc9ca69f92
Revises: 4656acfff03c
Create Date: 2026-07-05 23:14:48.830829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86dc9ca69f92'
down_revision: Union[str, Sequence[str], None] = '4656acfff03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_plans', sa.Column('daily_macros_target', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('nutrition_plans', sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('nutrition_plans', 'nutrition_data')
    op.drop_column('nutrition_plans', 'prompt_used')
    op.drop_index(op.f('ix_squad_notif_squad_created'), table_name='squad_notifications')
    op.create_index('ix_squad_notif_squad_created', 'squad_notifications', ['squad_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_squad_notif_squad_created', table_name='squad_notifications', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_squad_notif_squad_created'), 'squad_notifications', ['squad_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('nutrition_plans', sa.Column('prompt_used', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('nutrition_plans', sa.Column('nutrition_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('nutrition_plans', 'meals')
    op.drop_column('nutrition_plans', 'daily_macros_target')
    # ### end Alembic commands ###
