"""add_athlete_drafts_phase_25

Revision ID: 890fc896ee12
Revises: 4b0dd3c73e27
Create Date: 2026-03-07 10:52:26.013092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '890fc896ee12'
down_revision: Union[str, Sequence[str], None] = '4b0dd3c73e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('onboarding_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Estrés, Equipo, Lesiones, Video URL'),
    sa.Column('original_plan_id', sa.UUID(), nullable=True),
    sa.Column('mutated_routine', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='La rutina con ejercicios cambiados y MRV ajustado'),
    sa.Column('ai_reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array de justificaciones estructuradas por bloque o ejercicio'),
    sa.Column('risk_score', sa.String(length=20), nullable=False, comment='Green, Yellow, Red'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='pending_review, approved, discarded'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_plan_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_athlete_drafts_tenant_status', 'athlete_drafts', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_athlete_drafts_tenant_status', table_name='athlete_drafts')
    op.drop_table('athlete_drafts')
    # ### end Alembic commands ###
