"""add_tenant_branding

Revision ID: 8e7ea5c1c527
Revises: c7a1f2b3d4e5
Create Date: 2026-03-06 11:18:31.665662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7ea5c1c527'
down_revision: Union[str, Sequence[str], None] = 'c7a1f2b3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burnable_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burnable_links_token'), 'burnable_links', ['token'], unique=True)
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('primary_color', sa.String(length=7), server_default='#CEFF00', nullable=False))
    op.alter_column('tenants', 'compute_units_balance',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'compute_units_balance',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'500000'::bigint"),
               existing_nullable=False)
    op.drop_column('tenants', 'primary_color')
    op.drop_column('tenants', 'logo_url')
    op.drop_index(op.f('ix_burnable_links_token'), table_name='burnable_links')
    op.drop_table('burnable_links')
    # ### end Alembic commands ###
