"""Add mechanic and contraindications

Revision ID: 9a09ad0040b5
Revises: 0e6f9a705a0d
Create Date: 2026-03-17 10:43:03.803850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a09ad0040b5'
down_revision: Union[str, Sequence[str], None] = '0e6f9a705a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macrocycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='Tags originales de hipertrofia/fuerza target'),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Estructura jerárquica Semanas -> Días -> Bloques -> Ejercicios'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='PENDING_APPROVAL, ACTIVE, ARCHIVED'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_macrocycles_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['professionals.id'], name=op.f('fk_macrocycles_coach_id_professionals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_macrocycles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macrocycles'))
    )
    op.create_index('ix_macrocycles_tenant_status', 'macrocycles', ['tenant_id', 'status'], unique=False)
    op.drop_table('dtg_edges')
    op.drop_table('dtg_nodes')
    op.alter_column('athlete_drafts', 'training_experience',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('athlete_drafts', 'training_days_available',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('athlete_drafts', 'training_duration_pref',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('athlete_drafts', 'medical_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('athlete_drafts', 'goal_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('athlete_drafts', 'habit_sleep_quality',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('athlete_drafts', 'habit_stress_level',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('athlete_drafts', 'habit_work_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('athlete_wallets_client_id_key'), 'athlete_wallets', type_='unique')
    op.create_unique_constraint(op.f('uq_athlete_wallets_client_id'), 'athlete_wallets', ['client_id'])
    op.add_column('exercise_targets', sa.Column('custom_exercise_name', sa.String(length=255), nullable=True))
    op.alter_column('exercise_targets', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_exercise_targets_exercise_id_exercises'), 'exercise_targets', 'exercises', ['exercise_id'], ['id'], ondelete='SET NULL')
    op.add_column('exercises', sa.Column('mechanic', sa.String(length=50), nullable=True, comment='compound or isolation'))
    op.add_column('exercises', sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment="List of medical tags that prevent this exercise e.g. ['inj_lower_back']"))
    op.drop_constraint(op.f('invitations_token_key'), 'invitations', type_='unique')
    op.create_unique_constraint(op.f('uq_invitations_token'), 'invitations', ['token'])
    op.alter_column('protocols', 'type',
               existing_type=postgresql.ENUM('DIET', 'ROUTINE', 'SUPPLEMENT', 'RECOVERY', name='protocoltype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('push_subscriptions_endpoint_key'), 'push_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('uq_push_subscriptions_endpoint'), 'push_subscriptions', ['endpoint'])
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.create_unique_constraint(op.f('uq_tenants_slug'), 'tenants', ['slug'])
    op.drop_constraint(op.f('users_auth_provider_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_auth_provider_id'), 'users', ['auth_provider_id'])
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_auth_provider_id'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_auth_provider_id_key'), 'users', ['auth_provider_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_tenants_slug'), 'tenants', type_='unique')
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_push_subscriptions_endpoint'), 'push_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('push_subscriptions_endpoint_key'), 'push_subscriptions', ['endpoint'], postgresql_nulls_not_distinct=False)
    op.alter_column('protocols', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('DIET', 'ROUTINE', 'SUPPLEMENT', 'RECOVERY', name='protocoltype'),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_invitations_token'), 'invitations', type_='unique')
    op.create_unique_constraint(op.f('invitations_token_key'), 'invitations', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('exercises', 'contraindications')
    op.drop_column('exercises', 'mechanic')
    op.drop_constraint(op.f('fk_exercise_targets_exercise_id_exercises'), 'exercise_targets', type_='foreignkey')
    op.alter_column('exercise_targets', 'exercise_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('exercise_targets', 'custom_exercise_name')
    op.drop_constraint(op.f('uq_athlete_wallets_client_id'), 'athlete_wallets', type_='unique')
    op.create_unique_constraint(op.f('athlete_wallets_client_id_key'), 'athlete_wallets', ['client_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('athlete_drafts', 'habit_work_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'SEDENTARY'::character varying"),
               nullable=True)
    op.alter_column('athlete_drafts', 'habit_stress_level',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               nullable=True)
    op.alter_column('athlete_drafts', 'habit_sleep_quality',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               nullable=True)
    op.alter_column('athlete_drafts', 'goal_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('athlete_drafts', 'medical_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('athlete_drafts', 'training_duration_pref',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               nullable=True)
    op.alter_column('athlete_drafts', 'training_days_available',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               nullable=True)
    op.alter_column('athlete_drafts', 'training_experience',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'BEGINNER'::character varying"),
               nullable=True)
    op.create_table('dtg_nodes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('node_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_line', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dtg_nodes'))
    )
    op.create_table('dtg_edges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edge_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['dtg_nodes.id'], name=op.f('fk_dtg_edges_source_id_dtg_nodes')),
    sa.ForeignKeyConstraint(['target_id'], ['dtg_nodes.id'], name=op.f('fk_dtg_edges_target_id_dtg_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dtg_edges'))
    )
    op.drop_index('ix_macrocycles_tenant_status', table_name='macrocycles')
    op.drop_table('macrocycles')
    # ### end Alembic commands ###
