"""Phase_16_Drift_Protocol

Revision ID: 9c1cb12b46d7
Revises: c11699b4bd4a
Create Date: 2026-06-05 17:57:49.541279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c1cb12b46d7'
down_revision: Union[str, Sequence[str], None] = 'c11699b4bd4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m2m_audit_vault',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m2m_audit_vault'))
    )
    op.create_index(op.f('ix_m2m_audit_vault_client_id'), 'm2m_audit_vault', ['client_id'], unique=False)
    op.add_column('workout_sets', sa.Column('is_unscheduled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sets', 'is_unscheduled')
    op.drop_index(op.f('ix_m2m_audit_vault_client_id'), table_name='m2m_audit_vault')
    op.drop_table('m2m_audit_vault')
    # ### end Alembic commands ###
