"""phase_26_math_engine_status

Revision ID: a1acf92c4843
Revises: 02ebe20f7dd7
Create Date: 2026-06-07 01:03:10.539364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1acf92c4843'
down_revision: Union[str, Sequence[str], None] = '02ebe20f7dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sessions', sa.Column('math_status', sa.String(length=50), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sessions', 'math_status')
    # ### end Alembic commands ###
