"""snc_telemetry_models

Revision ID: a236445d5e37
Revises: 1b4cccf2f8f0
Create Date: 2026-03-06 19:40:02.749956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a236445d5e37'
down_revision: Union[str, Sequence[str], None] = '1b4cccf2f8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_readiness',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('logical_date', sa.Date(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('muscle_soreness', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id', 'logical_date', name='uq_athlete_logical_date')
    )
    op.create_index('ix_daily_readiness_athlete_date', 'daily_readiness', ['athlete_id', 'logical_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_readiness_athlete_date', table_name='daily_readiness')
    op.drop_table('daily_readiness')
    # ### end Alembic commands ###
