"""Add ExerciseTemplate with Core-Shell

Revision ID: a242a87c0bfa
Revises: 1a8074ec92f2
Create Date: 2026-05-28 19:16:03.716869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'a242a87c0bfa'
down_revision: Union[str, Sequence[str], None] = '1a8074ec92f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('primary_muscle_group', sa.String(length=50), nullable=False),
    sa.Column('axial_load', sa.Boolean(), nullable=False),
    sa.Column('is_glp1_safe', sa.Boolean(), nullable=False),
    sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aurea_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_templates'))
    )
    op.create_index(op.f('ix_exercise_templates_name'), 'exercise_templates', ['name'], unique=False)
    op.alter_column('athlete_drafts', 'habit_anchor',
               existing_type=sa.VARCHAR(length=255),
               comment="Hábito preexistente al que se ancla el entrenamiento (ej: 'Después de tomar mi café matutino')",
               existing_nullable=True)
    op.alter_column('clients', 'coaching_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='active, interim_maintenance',
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('clients', 'unassigned_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Días sin coach para Revenue Guard Prorrateo',
               existing_server_default=sa.text('0'))
    op.alter_column('consistency_trackers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('consistency_trackers', 'weekly_consistency_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('consistency_trackers', 'current_tier',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('consistency_trackers', 'grace_days_remaining',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('consistency_trackers', 'consecutive_active_weeks',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('consistency_trackers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('consistency_trackers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('master_templates', 'target_gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('micro_milestones', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('micro_milestones', 'is_achieved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('micro_milestones', 'xp_reward',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('micro_milestones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('squad_activities', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_activities', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_members', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_members', 'is_leader',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_members', 'current_streak',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_members', 'total_activities',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_members', 'streak_shields',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_notifications', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squad_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squads', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('squads', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('video_reviews', 'ai_priority',
               existing_type=sa.VARCHAR(length=10),
               comment='P1, P2, P3',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_reviews', 'ai_priority',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='P1, P2, P3',
               existing_nullable=True)
    op.alter_column('squads', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('squads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('squads', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('squad_notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('squad_notifications', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('squad_members', 'streak_shields',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('squad_members', 'total_activities',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('squad_members', 'current_streak',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('squad_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('squad_members', 'is_leader',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('squad_members', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('squad_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('squad_activities', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('squad_activities', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('micro_milestones', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('micro_milestones', 'xp_reward',
               existing_type=sa.INTEGER(),
               server_default=sa.text('50'),
               nullable=True)
    op.alter_column('micro_milestones', 'is_achieved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('micro_milestones', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('master_templates', 'target_gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('consistency_trackers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('consistency_trackers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('consistency_trackers', 'consecutive_active_weeks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('consistency_trackers', 'grace_days_remaining',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2'),
               nullable=True)
    op.alter_column('consistency_trackers', 'current_tier',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'BRONZE'::character varying"),
               nullable=True)
    op.alter_column('consistency_trackers', 'weekly_consistency_score',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('consistency_trackers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('clients', 'unassigned_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Días sin coach para Revenue Guard Prorrateo',
               existing_server_default=sa.text('0'))
    op.alter_column('clients', 'coaching_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='active, interim_maintenance',
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('athlete_drafts', 'habit_anchor',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Hábito preexistente al que se ancla el entrenamiento (ej: 'Después de tomar mi café matutino')",
               existing_nullable=True)
    op.drop_index(op.f('ix_exercise_templates_name'), table_name='exercise_templates')
    op.drop_table('exercise_templates')
    # ### end Alembic commands ###
