"""phase_43_scheduling_domain

Revision ID: aa4d63a456ac
Revises: 2373c2f87c06
Create Date: 2026-06-08 18:47:21.439038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa4d63a456ac'
down_revision: Union[str, Sequence[str], None] = '2373c2f87c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduling_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scheduling_resources_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_resources'))
    )
    op.create_index(op.f('ix_scheduling_resources_tenant_id'), 'scheduling_resources', ['tenant_id'], unique=False)
    op.create_table('scheduling_class_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('current_capacity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['scheduling_resources.id'], name=op.f('fk_scheduling_class_sessions_resource_id_scheduling_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_scheduling_class_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_class_sessions'))
    )
    op.create_index(op.f('ix_scheduling_class_sessions_resource_id'), 'scheduling_class_sessions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_scheduling_class_sessions_tenant_id'), 'scheduling_class_sessions', ['tenant_id'], unique=False)
    op.create_table('scheduling_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['scheduling_class_sessions.id'], name=op.f('fk_scheduling_reservations_session_id_scheduling_class_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scheduling_reservations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduling_reservations'))
    )
    op.create_index(op.f('ix_scheduling_reservations_billing_reference_id'), 'scheduling_reservations', ['billing_reference_id'], unique=False)
    op.create_index(op.f('ix_scheduling_reservations_idempotency_key'), 'scheduling_reservations', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_scheduling_reservations_session_id'), 'scheduling_reservations', ['session_id'], unique=False)
    op.create_index(op.f('ix_scheduling_reservations_user_id'), 'scheduling_reservations', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_scheduling_reservations_user_id'), table_name='scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_reservations_session_id'), table_name='scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_reservations_idempotency_key'), table_name='scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_reservations_billing_reference_id'), table_name='scheduling_reservations')
    op.drop_table('scheduling_reservations')
    op.drop_index(op.f('ix_scheduling_class_sessions_tenant_id'), table_name='scheduling_class_sessions')
    op.drop_index(op.f('ix_scheduling_class_sessions_resource_id'), table_name='scheduling_class_sessions')
    op.drop_table('scheduling_class_sessions')
    op.drop_index(op.f('ix_scheduling_resources_tenant_id'), table_name='scheduling_resources')
    op.drop_table('scheduling_resources')
    # ### end Alembic commands ###
