"""refactor_agnostic_payments

Revision ID: b0b47f01b18a
Revises: 5b127a409e56
Create Date: 2026-03-06 12:42:14.270231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0b47f01b18a'
down_revision: Union[str, Sequence[str], None] = '5b127a409e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type idempotently for Postgres
    conn = op.get_bind()
    conn.execute(sa.text("DO $$ BEGIN CREATE TYPE paymentprovider AS ENUM ('MERCADO_PAGO', 'STRIPE', 'NONE'); EXCEPTION WHEN duplicate_object THEN null; END $$;"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_payment_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),  # Use String temporarily
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    
    # Cast provider to Enum in processed_payment_events
    op.execute("ALTER TABLE processed_payment_events ALTER COLUMN provider TYPE paymentprovider USING provider::paymentprovider")
    
    op.create_index('ix_payment_events_provider_at', 'processed_payment_events', ['provider', 'processed_at'], unique=False)
    
    # Add column as String first, then cast
    op.add_column('tenants', sa.Column('payment_provider', sa.String(length=50), nullable=True))
    op.execute("UPDATE tenants SET payment_provider = 'NONE' WHERE payment_provider IS NULL")
    op.execute("ALTER TABLE tenants ALTER COLUMN payment_provider TYPE paymentprovider USING payment_provider::paymentprovider")
    op.execute("ALTER TABLE tenants ALTER COLUMN payment_provider SET DEFAULT 'NONE'::paymentprovider")
    op.execute("ALTER TABLE tenants ALTER COLUMN payment_provider SET NOT NULL")
    
    op.add_column('tenants', sa.Column('provider_subscription_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'provider_subscription_id')
    op.drop_column('tenants', 'payment_provider')
    op.drop_index('ix_payment_events_provider_at', table_name='processed_payment_events')
    op.drop_table('processed_payment_events')
    # ### end Alembic commands ###
    
    # Drop enum type explicitly
    sa.Enum('MERCADO_PAGO', 'STRIPE', 'NONE', name='paymentprovider').drop(op.get_bind())
