"""Add hybrid protocol engine

Revision ID: b1c4240da065
Revises: 1b275b188357
Create Date: 2026-06-04 12:33:21.993777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c4240da065'
down_revision: Union[str, Sequence[str], None] = '1b275b188357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.add_column('protocols', sa.Column('professional_id', sa.UUID(), nullable=False))
    op.add_column('protocols', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Estructura flexible: meals, exercises, supplements, etc.'))
    op.add_column('protocols', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_index(op.f('ix_protocols_active'), table_name='protocols')
    op.create_index('ix_protocols_status', 'protocols', ['status'], unique=False)
    op.create_index('ix_protocols_tenant_client', 'protocols', ['tenant_id', 'client_id'], unique=False)
    op.create_foreign_key(op.f('fk_protocols_professional_id_professionals'), 'protocols', 'professionals', ['professional_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_protocols_tenant_id_tenants'), 'protocols', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('protocols', 'data')
    op.drop_column('protocols', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protocols', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('protocols', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Estructura flexible: meals, exercises, supplements, etc.'))
    op.drop_constraint(op.f('fk_protocols_tenant_id_tenants'), 'protocols', type_='foreignkey')
    op.drop_constraint(op.f('fk_protocols_professional_id_professionals'), 'protocols', type_='foreignkey')
    op.drop_index('ix_protocols_tenant_client', table_name='protocols')
    op.drop_index('ix_protocols_status', table_name='protocols')
    op.create_index(op.f('ix_protocols_active'), 'protocols', ['is_active'], unique=False)
    op.drop_column('protocols', 'status')
    op.drop_column('protocols', 'content')
    op.drop_column('protocols', 'professional_id')
    op.drop_column('protocols', 'tenant_id')
    # ### end Alembic commands ###
