"""Add B2C Payment Models and Subscription Fields

Revision ID: b95045558568
Revises: 39eb4dbe8bd3
Create Date: 2026-03-02 01:42:46.793186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95045558568'
down_revision: Union[str, Sequence[str], None] = '39eb4dbe8bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_tenant_client', 'payments', ['tenant_id', 'client_id'], unique=False)
    op.add_column('clients', sa.Column('next_billing_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('professionals', sa.Column('subscription_status', sa.String(length=50), server_default='active', nullable=False))
    op.add_column('professionals', sa.Column('service_type', sa.String(length=50), server_default='fitness', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'service_type')
    op.drop_column('professionals', 'subscription_status')
    op.drop_column('clients', 'next_billing_date')
    op.drop_index('ix_payments_tenant_client', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
