"""Phase_15_protocol_id

Revision ID: c11699b4bd4a
Revises: 324cb07e1564
Create Date: 2026-06-05 13:14:13.137657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c11699b4bd4a'
down_revision: Union[str, Sequence[str], None] = '324cb07e1564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('protocol_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_workout_sets_protocol_id_protocols'), 'workout_sets', 'protocols', ['protocol_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # --- DATA MIGRATION (Phase 15 Backfill) ---
    # Busca el protocolo activo para el atleta en la fecha/hora de la serie
    op.execute("""
        UPDATE workout_sets ws
        SET protocol_id = p.id
        FROM protocols p
        WHERE p.client_id = ws.athlete_id
          AND p.type = 'ROUTINE'
          AND p.status = 'ACTIVE'
          AND (p.starts_at IS NULL OR p.starts_at <= ws.client_created_at)
          AND (p.ends_at IS NULL OR p.ends_at >= ws.client_created_at)
          AND ws.protocol_id IS NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workout_sets_protocol_id_protocols'), 'workout_sets', type_='foreignkey')
    op.drop_column('workout_sets', 'protocol_id')
    # ### end Alembic commands ###
