"""phase 20 cri snapshot

Revision ID: d1e2f3a4b5c6
Revises: 9c1cb12b46d7
Create Date: 2026-06-06 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1e2f3a4b5c6'
down_revision: Union[str, Sequence[str], None] = '9c1cb12b46d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_cri_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cri_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('factors_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='InactivityFactor, FatigueFactor, DisconnectionFactor'),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_cri_snapshots_calculated_at'), 'athlete_cri_snapshots', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_athlete_cri_snapshots_client_id'), 'athlete_cri_snapshots', ['client_id'], unique=False)
    op.create_index(op.f('ix_athlete_cri_snapshots_tenant_id'), 'athlete_cri_snapshots', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_cri_snapshots_tenant_id'), table_name='athlete_cri_snapshots')
    op.drop_index(op.f('ix_athlete_cri_snapshots_client_id'), table_name='athlete_cri_snapshots')
    op.drop_index(op.f('ix_athlete_cri_snapshots_calculated_at'), table_name='athlete_cri_snapshots')
    op.drop_table('athlete_cri_snapshots')
    # ### end Alembic commands ###
