"""Add scorecard_vault table

Revision ID: ddaf712d9a19
Revises: 4a89d2f9907e
Create Date: 2026-06-10 14:46:51.678534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddaf712d9a19'
down_revision: Union[str, Sequence[str], None] = '4a89d2f9907e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecard_vault',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_event_id', sa.UUID(), nullable=False),
    sa.Column('last_client_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id', name=op.f('pk_scorecard_vault'))
    )
    op.create_index('ix_gaming_tenant_xp', 'scorecard_vault', ['tenant_id', 'total_xp'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gaming_tenant_xp', table_name='scorecard_vault', postgresql_using='btree')
    op.drop_table('scorecard_vault')
    # ### end Alembic commands ###
