"""Add professional_id to ActionCard and ClassSession

Revision ID: e6926ea08b34
Revises: c5eab8b5f7d8
Create Date: 2026-06-09 11:11:17.755947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6926ea08b34'
down_revision: Union[str, Sequence[str], None] = 'c5eab8b5f7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_risk_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_churn_risk_scores'))
    )
    op.create_index(op.f('ix_churn_risk_scores_athlete_id'), 'churn_risk_scores', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_churn_risk_scores_calculated_at'), 'churn_risk_scores', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_churn_risk_scores_id'), 'churn_risk_scores', ['id'], unique=False)
    op.create_index(op.f('ix_churn_risk_scores_tenant_id'), 'churn_risk_scores', ['tenant_id'], unique=False)
    op.add_column('action_cards', sa.Column('professional_id', sa.UUID(), nullable=True))
    op.add_column('action_cards', sa.Column('risk_score_id', sa.UUID(), nullable=False))
    op.add_column('action_cards', sa.Column('title', sa.String(), nullable=False))
    op.add_column('action_cards', sa.Column('body_template', sa.String(), nullable=False))
    op.add_column('action_cards', sa.Column('context_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('idx_action_cards_tenant_pt_status', 'action_cards', ['tenant_id', 'professional_id', 'status'], unique=False)
    op.create_index(op.f('ix_action_cards_athlete_id'), 'action_cards', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_action_cards_id'), 'action_cards', ['id'], unique=False)
    op.create_index(op.f('ix_action_cards_professional_id'), 'action_cards', ['professional_id'], unique=False)
    op.create_index(op.f('ix_action_cards_status'), 'action_cards', ['status'], unique=False)
    op.create_index(op.f('ix_action_cards_tenant_id'), 'action_cards', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('fk_action_cards_template_id_action_card_templates'), 'action_cards', type_='foreignkey')
    op.create_foreign_key(op.f('fk_action_cards_risk_score_id_churn_risk_scores'), 'action_cards', 'churn_risk_scores', ['risk_score_id'], ['id'])
    op.drop_column('action_cards', 'context_payload')
    op.drop_column('action_cards', 'coach_id')
    op.drop_column('action_cards', 'template_id')
    op.drop_column('action_cards', 'was_useful')
    op.drop_column('action_cards', 'priority_score')
    op.add_column('patients', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Nutritional Profile & Clinical Archetypes via Pydantic'))
    op.add_column('scheduling_class_sessions', sa.Column('professional_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_scheduling_class_sessions_professional_id'), 'scheduling_class_sessions', ['professional_id'], unique=False)
    op.create_foreign_key(op.f('fk_scheduling_class_sessions_professional_id_users'), 'scheduling_class_sessions', 'users', ['professional_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_squad_notif_squad_created', 'squad_notifications', ['squad_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scheduling_class_sessions_professional_id_users'), 'scheduling_class_sessions', type_='foreignkey')
    op.drop_column('scheduling_class_sessions', 'professional_id')
    op.drop_column('patients', 'extra_data')
    op.add_column('action_cards', sa.Column('priority_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('action_cards', sa.Column('was_useful', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('action_cards', sa.Column('template_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('action_cards', sa.Column('coach_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('action_cards', sa.Column('context_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_action_cards_risk_score_id_churn_risk_scores'), 'action_cards', type_='foreignkey')
    op.create_foreign_key(op.f('fk_action_cards_template_id_action_card_templates'), 'action_cards', 'action_card_templates', ['template_id'], ['id'])
    op.create_index(op.f('ix_action_cards_coach_status'), 'action_cards', ['coach_id', 'status'], unique=False)
    op.drop_column('action_cards', 'context_variables')
    op.drop_column('action_cards', 'body_template')
    op.drop_column('action_cards', 'title')
    op.drop_column('action_cards', 'risk_score_id')
    op.drop_column('action_cards', 'professional_id')
    op.create_table('coach_communication_states',
    sa.Column('coach_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('unopened_streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('cooldown_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('coach_id', name=op.f('pk_coach_communication_states'))
    )
    op.create_table('growth_event_tracks_y2026m06',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('squad_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('growth_event_tracks_y2026m06_pkey'))
    )
    op.create_index(op.f('growth_event_tracks_y2026m06_squad_id_event_type_idx'), 'growth_event_tracks_y2026m06', ['squad_id', 'event_type'], unique=False)
    op.create_index(op.f('growth_event_tracks_y2026m06_created_at_idx'), 'growth_event_tracks_y2026m06', ['created_at'], unique=False)
    op.create_table('action_card_templates',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content_template', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('confidence_base', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_card_templates'))
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price_monthly', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_table('growth_event_tracks_y2026m07',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('squad_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('growth_event_tracks_y2026m07_pkey'))
    )
    op.create_index(op.f('growth_event_tracks_y2026m07_squad_id_event_type_idx'), 'growth_event_tracks_y2026m07', ['squad_id', 'event_type'], unique=False)
    op.create_index(op.f('growth_event_tracks_y2026m07_created_at_idx'), 'growth_event_tracks_y2026m07', ['created_at'], unique=False)
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ACTIVE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_tenant_subscriptions_plan_id_subscription_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_subscriptions')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_subscription'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tenant_subscription_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=False)
    op.create_table('growth_event_tracks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('squad_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('growth_event_tracks_pkey'))
    )
    op.create_index(op.f('ix_growth_events_squad_type'), 'growth_event_tracks', ['squad_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_growth_events_created'), 'growth_event_tracks', ['created_at'], unique=False)
    op.create_table('plan_capability_links',
    sa.Column('plan_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('capability_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['feature_capabilities.id'], name=op.f('fk_plan_capability_links_capability_id_feature_capabilities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_plan_capability_links_plan_id_subscription_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id', 'capability_id', name=op.f('pk_plan_capability_links'))
    )
    op.create_table('feature_capabilities',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_capabilities'))
    )
    op.create_table('notification_digest_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('coach_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('opened_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('clicked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_digest_logs')),
    sa.UniqueConstraint('coach_id', 'target_date', name=op.f('uq_digest_coach_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notif_digest_coach_date'), 'notification_digest_logs', ['coach_id', 'target_date'], unique=False)
    # ### end Alembic commands ###
