"""Add SaraFoodItem table for Smart Swaps

Revision ID: f31e03eca0df
Revises: 86dc9ca69f92
Create Date: 2026-07-06 16:57:17.438093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f31e03eca0df'
down_revision: Union[str, Sequence[str], None] = '86dc9ca69f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sara_food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('energy_kcal', sa.Float(), nullable=False),
    sa.Column('water_g', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False, comment='<PROCNT>'),
    sa.Column('available_carbs_g', sa.Float(), nullable=False, comment='<CHOAVLDF> (Carbohidratos Disponibles = Totales - Fibra)'),
    sa.Column('total_fat_g', sa.Float(), nullable=False, comment='<FATCE>'),
    sa.Column('dietary_fiber_g', sa.Float(), nullable=False, comment='<FIBTG> (Método AOAC)'),
    sa.Column('saturated_fat_g', sa.Float(), nullable=False),
    sa.Column('monounsaturated_fat_g', sa.Float(), nullable=False),
    sa.Column('polyunsaturated_fat_g', sa.Float(), nullable=False),
    sa.Column('trans_fat_g', sa.Float(), nullable=False),
    sa.Column('cholesterol_mg', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('is_cooked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sara_food_items'))
    )
    op.create_index(op.f('ix_sara_food_items_category'), 'sara_food_items', ['category'], unique=False)
    op.create_index(op.f('ix_sara_food_items_name'), 'sara_food_items', ['name'], unique=False)
    op.alter_column('active_workout_plans', 'origin_protocol_id',
               existing_type=sa.UUID(),
               comment='Arquetipo original del cual se derivÃ³ este plan activo',
               existing_comment='Arquetipo original del cual se derivó este plan activo',
               existing_nullable=True)
    op.alter_column('active_workout_plans', 'conflict_detected_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp de cuando se detectÃ³ la deriva con el origin_protocol',
               existing_comment='Timestamp de cuando se detectó la deriva con el origin_protocol',
               existing_nullable=True)
    op.alter_column('athlete_drafts', 'onboarding_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='EstrÃ©s, Equipo, Lesiones, Video URL',
               existing_comment='Estrés, Equipo, Lesiones, Video URL',
               existing_nullable=False)
    op.alter_column('athlete_drafts', 'habit_anchor',
               existing_type=sa.VARCHAR(length=255),
               comment="HÃ¡bito preexistente al que se ancla el entrenamiento (ej: 'DespuÃ©s de tomar mi cafÃ© matutino')",
               existing_comment="Hábito preexistente al que se ancla el entrenamiento (ej: 'Después de tomar mi café matutino')",
               existing_nullable=True)
    op.alter_column('clients', 'unassigned_days',
               existing_type=sa.INTEGER(),
               comment='DÃ\xadas sin coach para Revenue Guard Prorrateo',
               existing_comment='Días sin coach para Revenue Guard Prorrateo',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('macrocycles', 'structure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estructura jerÃ¡rquica Semanas -> DÃ\xadas -> Bloques -> Ejercicios',
               existing_comment='Estructura jerárquica Semanas -> Días -> Bloques -> Ejercicios',
               existing_nullable=False)
    op.alter_column('professionals', 'coaching_style',
               existing_type=sa.TEXT(),
               comment='DescripciÃ³n del estilo de coaching para RAG',
               existing_comment='Descripción del estilo de coaching para RAG',
               existing_nullable=True)
    op.alter_column('protocols', 'vector_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               comment='Embedding para bÃºsqueda semÃ¡ntica de protocolos',
               existing_comment='Embedding para búsqueda semántica de protocolos',
               existing_nullable=True)
    op.drop_index(op.f('ix_squad_notif_squad_created'), table_name='squad_notifications')
    op.create_index('ix_squad_notif_squad_created', 'squad_notifications', ['squad_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_squad_notif_squad_created', table_name='squad_notifications', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_squad_notif_squad_created'), 'squad_notifications', ['squad_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('protocols', 'vector_embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               comment='Embedding para búsqueda semántica de protocolos',
               existing_comment='Embedding para bÃºsqueda semÃ¡ntica de protocolos',
               existing_nullable=True)
    op.alter_column('professionals', 'coaching_style',
               existing_type=sa.TEXT(),
               comment='Descripción del estilo de coaching para RAG',
               existing_comment='DescripciÃ³n del estilo de coaching para RAG',
               existing_nullable=True)
    op.alter_column('macrocycles', 'structure',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estructura jerárquica Semanas -> Días -> Bloques -> Ejercicios',
               existing_comment='Estructura jerÃ¡rquica Semanas -> DÃ\xadas -> Bloques -> Ejercicios',
               existing_nullable=False)
    op.alter_column('clients', 'unassigned_days',
               existing_type=sa.INTEGER(),
               comment='Días sin coach para Revenue Guard Prorrateo',
               existing_comment='DÃ\xadas sin coach para Revenue Guard Prorrateo',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('athlete_drafts', 'habit_anchor',
               existing_type=sa.VARCHAR(length=255),
               comment="Hábito preexistente al que se ancla el entrenamiento (ej: 'Después de tomar mi café matutino')",
               existing_comment="HÃ¡bito preexistente al que se ancla el entrenamiento (ej: 'DespuÃ©s de tomar mi cafÃ© matutino')",
               existing_nullable=True)
    op.alter_column('athlete_drafts', 'onboarding_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Estrés, Equipo, Lesiones, Video URL',
               existing_comment='EstrÃ©s, Equipo, Lesiones, Video URL',
               existing_nullable=False)
    op.alter_column('active_workout_plans', 'conflict_detected_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp de cuando se detectó la deriva con el origin_protocol',
               existing_comment='Timestamp de cuando se detectÃ³ la deriva con el origin_protocol',
               existing_nullable=True)
    op.alter_column('active_workout_plans', 'origin_protocol_id',
               existing_type=sa.UUID(),
               comment='Arquetipo original del cual se derivó este plan activo',
               existing_comment='Arquetipo original del cual se derivÃ³ este plan activo',
               existing_nullable=True)
    op.drop_index(op.f('ix_sara_food_items_name'), table_name='sara_food_items')
    op.drop_index(op.f('ix_sara_food_items_category'), table_name='sara_food_items')
    op.drop_table('sara_food_items')
    # ### end Alembic commands ###
