import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  CalendarDays, Clock, Plus, Users, Dumbbell, Apple, Video, 
  CheckCircle2, ChevronLeft, ChevronRight, MapPin, ExternalLink,
  Sparkles, CheckSquare, ListTodo, X, BellRing, Hourglass, 
  ArrowRight, Calendar as CalendarIcon, Ruler, Scale, Activity,
  HeartPulse, PlusCircle, Tag, Check
} from 'lucide-react';
import toast from 'react-hot-toast';
import { useNavigate } from 'react-router-dom';

export interface ServiceTypeOption {
  id: string;
  name: string;
  emoji: string;
  defaultTitle: string;
  colorClass: string;
  isCustom?: boolean;
}

export const DEFAULT_SERVICE_TYPES: ServiceTypeOption[] = [
  { id: 'WORKOUT_1ON1', name: 'Sesión 1 a 1 (Entrenamiento)', emoji: '🏋️', defaultTitle: 'Entrenamiento 1 a 1', colorClass: 'bg-amber-50 dark:bg-amber-950/60 text-amber-700 dark:text-amber-400 border-amber-200 dark:border-amber-800' },
  { id: 'ANTHROPOMETRY', name: 'Medición Antropométrica (ISAK / Pliegues)', emoji: '📏', defaultTitle: 'Medición Antropométrica (ISAK / Pliegues)', colorClass: 'bg-cyan-50 dark:bg-cyan-950/60 text-cyan-700 dark:text-cyan-400 border-cyan-200 dark:border-cyan-800' },
  { id: 'PHYSICAL_EVALUATION', name: 'Evaluación Física & Test 1RM', emoji: '⚖️', defaultTitle: 'Evaluación Física & Test de 1RM', colorClass: 'bg-violet-50 dark:bg-violet-950/60 text-violet-700 dark:text-violet-400 border-violet-200 dark:border-violet-800' },
  { id: 'POSTURAL_EVAL', name: 'Evaluación Postural & Movilidad', emoji: '🩺', defaultTitle: 'Evaluación Postural & Movilidad', colorClass: 'bg-teal-50 dark:bg-teal-950/60 text-teal-700 dark:text-teal-400 border-teal-200 dark:border-teal-800' },
  { id: 'NUTRITION', name: 'Consulta Nutricional', emoji: '🥗', defaultTitle: 'Consulta Nutricional', colorClass: 'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800' },
  { id: 'GROUP_CLASS', name: 'Clase Grupal', emoji: '👥', defaultTitle: 'Clase Grupal', colorClass: 'bg-purple-50 dark:bg-purple-950/60 text-purple-700 dark:text-purple-400 border-purple-200 dark:border-purple-800' },
];

export interface Appointment {
  id: string;
  athleteName: string;
  athleteAvatar: string;
  type: string;
  customServiceName?: string;
  customServiceEmoji?: string;
  title: string;
  date: string; // YYYY-MM-DD
  timeStart: string; // HH:MM
  timeEnd: string; // HH:MM
  format: 'IN_PERSON' | 'GOOGLE_MEET' | 'WHATSAPP';
  locationOrLink?: string;
  status: 'CONFIRMED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  notes?: string;
}

export interface CoachTask {
  id: string;
  title: string;
  category: 'CYCLE_RENEWAL' | 'PLAN' | 'VALIDATION' | 'CLIENT' | 'ADMIN';
  dueDate: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  completed: boolean;
  // Campos para Renovación Automática de Ciclos (7 días antes)
  isAutoGenerated?: boolean;
  athleteId?: string;
  athleteName?: string;
  athleteAvatar?: string;
  cycleType?: 'WORKOUT_CYCLE' | 'NUTRITION_CYCLE';
  cycleName?: string;
  daysRemaining?: number;
  expirationDate?: string;
  actionRoute?: string;
}

const INITIAL_APPOINTMENTS: Appointment[] = [];

const INITIAL_TASKS: CoachTask[] = [];

const TIME_SLOTS = [
  '08:00', '09:00', '10:00', '11:00', '12:00', 
  '13:00', '14:00', '15:00', '16:00', '17:00', 
  '18:00', '19:00', '20:00'
];

const getCurrentWeekDates = () => {
  const now = new Date();
  const currentDay = now.getDay();
  const diffToMonday = now.getDate() - currentDay + (currentDay === 0 ? -6 : 1);
  const monday = new Date(now.getFullYear(), now.getMonth(), diffToMonday);

  const dayNames = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'];
  const dayKeys = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];

  return dayKeys.map((key, index) => {
    const dayDate = new Date(monday.getFullYear(), monday.getMonth(), monday.getDate() + index);
    const dateStr = dayDate.toLocaleDateString('es-ES', { day: 'numeric', month: 'short' });
    const fullDate = dayDate.toISOString().split('T')[0];
    return { key, name: dayNames[index], dateStr, fullDate };
  });
};

const WEEK_DAYS = getCurrentWeekDates();

const EMOJI_OPTIONS = ['✨', '💆', '🧠', '🏊', '🥊', '🧘', '🚴', '🎯', '🏃', '🧊', '🩺', '🔥'];

export const ProfessionalAgenda: React.FC = () => {
  const navigate = useNavigate();
  const [appointments, setAppointments] = useState<Appointment[]>(INITIAL_APPOINTMENTS);
  const [tasks, setTasks] = useState<CoachTask[]>(INITIAL_TASKS);
  const [serviceTypes, setServiceTypes] = useState<ServiceTypeOption[]>(DEFAULT_SERVICE_TYPES);
  
  // Tab principal
  const [activeTab, setActiveTab] = useState<'CALENDAR' | 'TASKS' | 'SCHEDULE'>('CALENDAR');
  const [taskFilter, setTaskFilter] = useState<'ALL' | 'CYCLE' | 'MANUAL'>('ALL');
  
  // Modals
  const [isAppointmentModalOpen, setIsAppointmentModalOpen] = useState(false);
  const [isTaskModalOpen, setIsTaskModalOpen] = useState(false);
  const [isCycleConfigModalOpen, setIsCycleConfigModalOpen] = useState(false);
  
  // Modo creación de servicio personalizado dentro del modal
  const [isCreatingCustomService, setIsCreatingCustomService] = useState(false);
  const [customServiceName, setCustomServiceName] = useState('');
  const [customServiceEmoji, setCustomServiceEmoji] = useState('✨');

  // Formulario de Agendar Turno
  const [newApt, setNewApt] = useState({
    athleteName: '',
    title: '',
    type: 'WORKOUT_1ON1',
    date: new Date().toISOString().split('T')[0],
    timeStart: '10:00',
    timeEnd: '11:00',
    format: 'IN_PERSON' as Appointment['format'],
    locationOrLink: '',
    notes: ''
  });

  // Formulario de Nueva Tarea
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [newTaskCategory, setNewTaskCategory] = useState<CoachTask['category']>('PLAN');
  const [newTaskPriority, setNewTaskPriority] = useState<CoachTask['priority']>('HIGH');

  // Auto-sugerir título al cambiar tipo de servicio
  const handleServiceTypeChange = (selectedTypeId: string) => {
    if (selectedTypeId === 'CREATE_CUSTOM') {
      setIsCreatingCustomService(true);
      return;
    }

    const matchedService = serviceTypes.find(s => s.id === selectedTypeId);
    setNewApt(prev => ({
      ...prev,
      type: selectedTypeId,
      title: matchedService ? matchedService.defaultTitle : prev.title
    }));
  };

  // Guardar nuevo servicio personalizado
  const handleSaveCustomService = () => {
    if (!customServiceName.trim()) {
      toast.error('Escribe el nombre del servicio');
      return;
    }

    const newId = `CUSTOM_${Date.now()}`;
    const newService: ServiceTypeOption = {
      id: newId,
      name: `${customServiceEmoji} ${customServiceName.trim()}`,
      emoji: customServiceEmoji,
      defaultTitle: customServiceName.trim(),
      colorClass: 'bg-fuchsia-50 dark:bg-fuchsia-950/60 text-fuchsia-700 dark:text-fuchsia-400 border-fuchsia-200 dark:border-fuchsia-800',
      isCustom: true
    };

    setServiceTypes(prev => [...prev, newService]);
    setNewApt(prev => ({
      ...prev,
      type: newId,
      title: customServiceName.trim()
    }));
    
    setIsCreatingCustomService(false);
    setCustomServiceName('');
    toast.success(`Servicio "${customServiceName.trim()}" agregado`, { icon: '✨' });
  };

  // Asignar turno rápido haciendo clic en celda libre
  const handleQuickBookSlot = (date: string, time: string) => {
    const [hourStr, minStr] = time.split(':');
    const endHour = String(Number(hourStr) + 1).padStart(2, '0');
    setNewApt({
      athleteName: '',
      title: 'Entrenamiento 1 a 1',
      type: 'WORKOUT_1ON1',
      date: date || new Date().toISOString().split('T')[0],
      timeStart: time,
      timeEnd: `${endHour}:${minStr || '00'}`,
      format: 'IN_PERSON',
      locationOrLink: 'Gimnasio Central',
      notes: ''
    });
    setIsCreatingCustomService(false);
    setIsAppointmentModalOpen(true);
  };

  // Crear Turno
  const handleCreateAppointment = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newApt.athleteName.trim()) {
      toast.error('Por favor escribe el nombre del atleta');
      return;
    }

    const matchedService = serviceTypes.find(s => s.id === newApt.type);

    const created: Appointment = {
      id: `apt-${Date.now()}`,
      athleteName: newApt.athleteName.trim(),
      athleteAvatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
      type: newApt.type,
      customServiceName: matchedService?.name,
      customServiceEmoji: matchedService?.emoji,
      title: newApt.title || matchedService?.defaultTitle || 'Sesión Agendada',
      date: newApt.date,
      timeStart: newApt.timeStart,
      timeEnd: newApt.timeEnd,
      format: newApt.format,
      locationOrLink: newApt.locationOrLink || (newApt.format === 'IN_PERSON' ? 'Gimnasio Central' : 'Google Meet'),
      status: 'CONFIRMED',
      notes: newApt.notes
    };

    setAppointments(prev => [created, ...prev]);
    setIsAppointmentModalOpen(false);
    toast.success('¡Turno guardado con éxito!', { icon: '📅' });
  };

  // Marcar Tarea como completada
  const handleToggleTask = (id: string) => {
    setTasks(prev => prev.map(t => {
      if (t.id === id) {
        const nextState = !t.completed;
        if (nextState) toast.success('¡Tarea completada!', { icon: '🎉', duration: 1500 });
        return { ...t, completed: nextState };
      }
      return t;
    }));
  };

  // Agregar Tarea
  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTaskTitle.trim()) return;

    const created: CoachTask = {
      id: `task-${Date.now()}`,
      title: newTaskTitle.trim(),
      category: newTaskCategory,
      dueDate: 'Hoy',
      priority: newTaskPriority,
      completed: false
    };

    setTasks(prev => [created, ...prev]);
    setNewTaskTitle('');
    setIsTaskModalOpen(false);
    toast.success('Tarea agregada a tu lista', { icon: '📌' });
  };

  // Tareas filtradas
  const filteredTasks = useMemo(() => {
    if (taskFilter === 'CYCLE') return tasks.filter(t => t.category === 'CYCLE_RENEWAL');
    if (taskFilter === 'MANUAL') return tasks.filter(t => t.category !== 'CYCLE_RENEWAL');
    return tasks;
  }, [tasks, taskFilter]);

  const cycleTasks = useMemo(() => {
    return tasks.filter(t => t.category === 'CYCLE_RENEWAL' && !t.completed);
  }, [tasks]);

  const stats = useMemo(() => {
    const today = new Date().toISOString().split('T')[0];
    const todayApts = appointments.filter(a => a.date === today && a.status !== 'CANCELLED');
    const pendingTasks = tasks.filter(t => !t.completed);
    const completedTasks = tasks.filter(t => t.completed);
    const expiringCyclesCount = cycleTasks.length;

    return {
      todayAptsCount: todayApts.length,
      pendingTasksCount: pendingTasks.length,
      completedTasksCount: completedTasks.length,
      expiringCyclesCount
    };
  }, [appointments, tasks, cycleTasks]);

  // Helper para renderizar etiqueta de tipo de servicio
  const renderServiceBadge = (typeId: string) => {
    const service = serviceTypes.find(s => s.id === typeId);
    if (!service) {
      return (
        <span className="text-[9px] font-black uppercase px-2 py-0.5 rounded-md bg-purple-50 dark:bg-purple-950/60 text-purple-700 dark:text-purple-400 border border-purple-200 dark:border-purple-800 flex items-center gap-1">
          ✨ {typeId}
        </span>
      );
    }

    return (
      <span className={`text-[9px] font-black uppercase px-2 py-0.5 rounded-md border flex items-center gap-1 ${service.colorClass}`}>
        <span>{service.emoji}</span>
        <span>{service.defaultTitle}</span>
      </span>
    );
  };

  return (
    <div className="flex-1 flex flex-col space-y-5 font-lato max-w-7xl mx-auto p-3 md:p-6">
      
      {/* 🌟 1. CABECERA LIMPIA & PEDAGÓGICA */}
      <div className="flex flex-col md:flex-row gap-4 items-start md:items-center justify-between bg-white dark:bg-[#0a0d16] p-5 md:p-6 rounded-3xl border border-slate-200/80 dark:border-zinc-800 shadow-xs">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[10px] font-black uppercase tracking-wider text-indigo-600 dark:text-indigo-400 font-mono">
              TU CENTRO DE TIEMPO & GESTIÓN
            </span>
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
          </div>
          <h1 className="text-2xl md:text-3xl font-black font-montserrat tracking-tight text-slate-900 dark:text-white">
            Tu Agenda Semanal
          </h1>
          <p className="text-xs text-slate-500 dark:text-zinc-400 mt-1 max-w-xl">
            Todo organizado en un solo lugar: entrenamientos, mediciones, servicios personalizados y tareas del día.
          </p>
        </div>

        {/* Acciones Rápidas */}
        <div className="flex flex-wrap items-center gap-2 w-full md:w-auto justify-end">
          <button
            onClick={() => setIsCycleConfigModalOpen(true)}
            className="py-2 px-3 rounded-2xl bg-amber-50 dark:bg-amber-950/60 border border-amber-200 dark:border-amber-800 text-amber-700 dark:text-amber-300 text-xs font-bold font-montserrat flex items-center gap-1.5 transition-all shadow-2xs hover:bg-amber-100 dark:hover:bg-amber-900"
            title="Configurar recordatorios de fin de mesociclo"
          >
            <BellRing size={14} className="text-amber-500" />
            <span>Avisos de Ciclo (7d)</span>
          </button>

          <button
            onClick={() => setIsTaskModalOpen(true)}
            className="py-2 px-3.5 rounded-2xl bg-slate-100 hover:bg-slate-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-slate-700 dark:text-zinc-200 text-xs font-bold font-montserrat flex items-center gap-1.5 transition-all shadow-2xs active:scale-95"
          >
            <CheckSquare size={14} className="text-emerald-500" />
            <span>+ Nueva Tarea</span>
          </button>

          <button
            onClick={() => {
              setNewApt({
                athleteName: '',
                title: 'Entrenamiento 1 a 1',
                type: 'WORKOUT_1ON1',
                date: new Date().toISOString().split('T')[0],
                timeStart: '10:00',
                timeEnd: '11:00',
                format: 'IN_PERSON',
                locationOrLink: 'Gimnasio Central',
                notes: ''
              });
              setIsCreatingCustomService(false);
              setIsAppointmentModalOpen(true);
            }}
            className="py-2 px-4 rounded-2xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold font-montserrat flex items-center gap-2 shadow-sm transition-all active:scale-95"
          >
            <Plus size={15} />
            <span>+ Agendar Turno</span>
          </button>
        </div>
      </div>

      {/* 🌟 2. TARJETAS DE RESUMEN (PEDAGOGÍA VISUAL) */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        {/* Card 1: Turnos Hoy */}
        <div 
          onClick={() => setActiveTab('SCHEDULE')}
          className="p-4 rounded-2xl bg-white dark:bg-[#0a0d16] border border-slate-200/80 dark:border-zinc-800 shadow-2xs flex items-center gap-3 cursor-pointer hover:border-indigo-400 transition-all"
        >
          <div className="w-10 h-10 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 flex items-center justify-center font-bold shrink-0">
            <CalendarDays size={18} />
          </div>
          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Turnos de Hoy</span>
            <span className="text-lg font-black text-slate-900 dark:text-white font-montserrat">
              {stats.todayAptsCount} Citas
            </span>
          </div>
        </div>

        {/* Card 2: Planes por Vencer */}
        <div 
          onClick={() => {
            setActiveTab('TASKS');
            setTaskFilter('CYCLE');
          }}
          className="p-4 rounded-2xl bg-amber-50/50 dark:bg-amber-950/20 border border-amber-200/80 dark:border-amber-800/60 shadow-2xs flex items-center gap-3 cursor-pointer hover:border-amber-400 transition-all"
        >
          <div className="w-10 h-10 rounded-2xl bg-amber-500/20 text-amber-600 dark:text-amber-400 flex items-center justify-center font-bold shrink-0">
            <Hourglass size={18} className="animate-pulse" />
          </div>
          <div>
            <span className="text-[10px] font-bold text-amber-700 dark:text-amber-400 uppercase tracking-wider block">Planes por Vencer</span>
            <span className="text-lg font-black text-slate-900 dark:text-white font-montserrat">
              {stats.expiringCyclesCount} Atletas (&lt; 7d)
            </span>
          </div>
        </div>

        {/* Card 3: Tareas Pendientes */}
        <div 
          onClick={() => {
            setActiveTab('TASKS');
            setTaskFilter('ALL');
          }}
          className="p-4 rounded-2xl bg-white dark:bg-[#0a0d16] border border-slate-200/80 dark:border-zinc-800 shadow-2xs flex items-center gap-3 cursor-pointer hover:border-blue-400 transition-all"
        >
          <div className="w-10 h-10 rounded-2xl bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 flex items-center justify-center font-bold shrink-0">
            <ListTodo size={18} />
          </div>
          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Tareas por Hacer</span>
            <span className="text-lg font-black text-slate-900 dark:text-white font-montserrat">
              {stats.pendingTasksCount} Pendientes
            </span>
          </div>
        </div>

        {/* Card 4: Tareas Listas */}
        <div className="p-4 rounded-2xl bg-white dark:bg-[#0a0d16] border border-slate-200/80 dark:border-zinc-800 shadow-2xs flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center font-bold shrink-0">
            <CheckCircle2 size={18} />
          </div>
          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Tareas Listas</span>
            <span className="text-lg font-black text-slate-900 dark:text-white font-montserrat">
              {stats.completedTasksCount} Completadas
            </span>
          </div>
        </div>
      </div>

      {/* 🌟 3. SWITCH DE VISTA: 3 PESTAÑAS SIMPLES */}
      <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between bg-white dark:bg-[#0a0d16] p-2.5 rounded-2xl border border-slate-200/80 dark:border-zinc-800">
        
        {/* Pestañas Principales */}
        <div className="flex flex-wrap bg-slate-100 dark:bg-zinc-900 p-1 rounded-xl border border-slate-200/80 dark:border-zinc-800 gap-1">
          <button
            onClick={() => setActiveTab('CALENDAR')}
            className={`py-1.5 px-3.5 rounded-lg text-xs font-bold font-montserrat transition-all flex items-center gap-1.5 ${
              activeTab === 'CALENDAR'
                ? 'bg-white dark:bg-zinc-800 text-indigo-600 dark:text-indigo-400 shadow-xs'
                : 'text-slate-500 dark:text-zinc-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <CalendarIcon size={13} />
            <span>Calendario Semanal (Libre / Ocupado)</span>
          </button>

          <button
            onClick={() => setActiveTab('TASKS')}
            className={`py-1.5 px-3.5 rounded-lg text-xs font-bold font-montserrat transition-all flex items-center gap-1.5 ${
              activeTab === 'TASKS'
                ? 'bg-white dark:bg-zinc-800 text-emerald-600 dark:text-emerald-400 shadow-xs'
                : 'text-slate-500 dark:text-zinc-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <ListTodo size={13} />
            <span>Avisos de Ciclo & Tareas ({stats.pendingTasksCount})</span>
          </button>

          <button
            onClick={() => setActiveTab('SCHEDULE')}
            className={`py-1.5 px-3.5 rounded-lg text-xs font-bold font-montserrat transition-all flex items-center gap-1.5 ${
              activeTab === 'SCHEDULE'
                ? 'bg-white dark:bg-zinc-800 text-sky-600 dark:text-sky-400 shadow-xs'
                : 'text-slate-500 dark:text-zinc-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <Clock size={13} />
            <span>Lista de Turnos de Hoy ({appointments.length})</span>
          </button>
        </div>

        {/* Guía Visual Rápida */}
        <div className="flex items-center gap-3 text-xs px-2">
          <span className="flex items-center gap-1.5 text-emerald-600 dark:text-emerald-400 font-bold">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500"></span>
            <span>Libre</span>
          </span>
          <span className="flex items-center gap-1.5 text-indigo-600 dark:text-indigo-400 font-bold">
            <span className="w-2.5 h-2.5 rounded-full bg-indigo-500"></span>
            <span>Turno Ocupado</span>
          </span>
        </div>
      </div>

      {/* 🌟 4. CONTENIDO SEGÚN LA PESTAÑA SELECCIONADA */}
      {activeTab === 'CALENDAR' ? (
        /* ═══════════════════════════════════════════════════════════════
           PESTAÑA 1: CALENDARIO SEMANAL VISUAL (LIBRE / OCUPADO)
           ═══════════════════════════════════════════════════════════════ */
        <div className="space-y-3">
          
          {/* Barra de navegación de la semana */}
          <div className="flex flex-col sm:flex-row gap-2 items-start sm:items-center justify-between px-1">
            <div className="flex items-center gap-2">
              <div className="flex bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl p-0.5">
                <button className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-zinc-800 text-slate-500">
                  <ChevronLeft size={16} />
                </button>
                <button className="p-1.5 rounded-lg hover:bg-slate-100 dark:hover:bg-zinc-800 text-slate-500">
                  <ChevronRight size={16} />
                </button>
              </div>
              <h2 className="text-sm md:text-base font-black font-montserrat text-slate-900 dark:text-white">
                Semana Actual: {WEEK_DAYS[0]?.dateStr} al {WEEK_DAYS[6]?.dateStr}
              </h2>
            </div>

            <div className="text-xs text-slate-500 dark:text-zinc-400 flex items-center gap-1">
              <Sparkles size={12} className="text-emerald-500" />
              <span>Toca cualquier casilla libre para asignar un turno en 1 segundo.</span>
            </div>
          </div>

          {/* Cuadrícula Semanal con Scroll Horizontal Seguro para Móviles */}
          <div className="bg-white dark:bg-[#0a0d16] border border-slate-200/80 dark:border-zinc-800 rounded-3xl overflow-x-auto shadow-xs">
            <div className="min-w-[700px]">
            
            {/* Cabecera de Días */}
            <div className="grid grid-cols-8 border-b border-slate-200 dark:border-zinc-800 bg-slate-50/80 dark:bg-zinc-900/60 text-center text-xs font-black font-montserrat">
              <div className="py-3 px-2 border-r border-slate-200 dark:border-zinc-800 text-slate-400 font-mono">
                HORA
              </div>
              {WEEK_DAYS.map((day) => {
                const todayStr = new Date().toISOString().split('T')[0];
                const isToday = day.fullDate === todayStr;
                return (
                  <div
                    key={day.key}
                    className={`py-3 px-1 border-r border-slate-200 dark:border-zinc-800 last:border-r-0 ${
                      isToday ? 'bg-indigo-50/70 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400' : 'text-slate-700 dark:text-zinc-300'
                    }`}
                  >
                    <span className="block text-[11px] uppercase tracking-wider">{day.name}</span>
                    <span className="block text-xs font-mono font-bold">{day.dateStr}</span>
                  </div>
                );
              })}
            </div>

            {/* Filas de Horas */}
            <div className="divide-y divide-slate-100 dark:divide-zinc-900">
              {TIME_SLOTS.map((time) => (
                <div key={time} className="grid grid-cols-8 min-h-[58px]">
                  
                  {/* Hora */}
                  <div className="p-2 border-r border-slate-200 dark:border-zinc-800 flex items-center justify-center text-xs font-mono font-bold text-slate-400 bg-slate-50/30 dark:bg-zinc-900/10">
                    {time}
                  </div>

                  {/* 7 Días */}
                  {WEEK_DAYS.map((day) => {
                    const slotHour = parseInt(time.split(':')[0], 10);
                    
                    const matchingApt = appointments.find(a => {
                      const aptHour = parseInt(a.timeStart.split(':')[0], 10);
                      return (a.date === day.fullDate || a.date === day.dateStr) && aptHour === slotHour;
                    });

                    if (matchingApt) {
                      const service = serviceTypes.find(s => s.id === matchingApt.type);
                      return (
                        <div
                          key={day.key}
                          className="p-1 border-r border-slate-100 dark:border-zinc-900 last:border-r-0 bg-indigo-50/40 dark:bg-indigo-950/20"
                        >
                          <div className="h-full w-full p-2 rounded-xl bg-indigo-600 text-white shadow-xs flex flex-col justify-between cursor-pointer hover:bg-indigo-500 transition-colors">
                            <div className="flex items-center justify-between gap-1">
                              <span className="text-[10px] font-mono font-bold text-indigo-100">
                                {matchingApt.timeStart}
                              </span>
                              <span className="text-[8px] font-black uppercase px-1 py-0.2 rounded bg-white/20 truncate max-w-[50px]">
                                {service ? `${service.emoji} ${service.defaultTitle.slice(0, 6)}` : 'Turno'}
                              </span>
                            </div>
                            <span className="text-xs font-black font-montserrat truncate block">
                              {matchingApt.athleteName}
                            </span>
                          </div>
                        </div>
                      );
                    }

                    // Celda Libre
                    return (
                      <div
                        key={day.key}
                        onClick={() => handleQuickBookSlot(day.fullDate, time)}
                        className="p-1 border-r border-slate-100 dark:border-zinc-900 last:border-r-0 group cursor-pointer hover:bg-emerald-50/40 dark:hover:bg-emerald-950/20 transition-colors"
                      >
                        <div className="h-full w-full rounded-xl border border-dashed border-slate-200/80 dark:border-zinc-800 group-hover:border-emerald-400 dark:group-hover:border-emerald-600 flex items-center justify-center transition-all p-1">
                          <span className="text-[10px] font-bold text-slate-300 dark:text-zinc-700 group-hover:text-emerald-600 dark:group-hover:text-emerald-400 group-hover:scale-105 transition-all flex items-center gap-0.5">
                            <Plus size={11} />
                            <span>Libre</span>
                          </span>
                        </div>
                      </div>
                    );
                  })}

                </div>
              ))}
            </div>

          </div>
        </div>
      </div>
      ) : activeTab === 'TASKS' ? (
        /* ═══════════════════════════════════════════════════════════════
           PESTAÑA 2: AVISOS DE FIN DE CICLO & LISTA DE TAREAS
           ═══════════════════════════════════════════════════════════════ */
        <div className="space-y-5">
          
          {/* BANNER EDUCATIVO & ACCIONABLE DE RENOVACIONES (< 7 DÍAS) */}
          {cycleTasks.length > 0 && (
            <div className="p-5 rounded-3xl bg-gradient-to-br from-amber-500/10 via-amber-500/5 to-transparent border border-amber-500/30 space-y-3">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <div className="flex items-center gap-2 text-amber-800 dark:text-amber-300 font-black font-montserrat text-xs uppercase tracking-wider">
                  <Hourglass size={16} className="text-amber-500" />
                  <span>Avisos Automáticos: Planes por Terminar en Menos de 7 Días ({cycleTasks.length})</span>
                </div>
                <span className="text-[11px] font-bold text-amber-700 dark:text-amber-400">
                  💡 Prepárales su próximo ciclo antes de que terminen
                </span>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {cycleTasks.map((task) => (
                  <div
                    key={task.id}
                    className="p-4 rounded-2xl bg-white dark:bg-zinc-900 border border-amber-200/80 dark:border-amber-800/60 shadow-xs flex flex-col justify-between space-y-3 hover:border-amber-500 transition-all"
                  >
                    <div className="space-y-2">
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex items-center gap-2">
                          <img src={task.athleteAvatar} alt={task.athleteName} className="w-8 h-8 rounded-full object-cover ring-2 ring-amber-400/50" />
                          <div>
                            <h4 className="text-xs font-black font-montserrat text-slate-900 dark:text-white">
                              {task.athleteName}
                            </h4>
                            <span className="text-[10px] font-mono text-slate-400">{task.expirationDate}</span>
                          </div>
                        </div>

                        <span className="text-[9px] font-black uppercase px-2 py-0.5 rounded-md bg-amber-100 dark:bg-amber-950 text-amber-800 dark:text-amber-300 font-mono">
                          ⏳ Quedan {task.daysRemaining} días
                        </span>
                      </div>

                      <div className="p-2.5 rounded-xl bg-slate-50 dark:bg-zinc-800/80 border border-slate-100 dark:border-zinc-700/80">
                        <div className="flex items-center gap-1.5 text-xs font-bold text-slate-800 dark:text-zinc-200 mb-0.5">
                          {task.cycleType === 'WORKOUT_CYCLE' ? <Dumbbell size={13} className="text-indigo-500" /> : <Apple size={13} className="text-emerald-500" />}
                          <span className="truncate">{task.cycleName}</span>
                        </div>
                        <p className="text-[11px] text-slate-500">
                          {task.cycleType === 'WORKOUT_CYCLE' ? 'Planificar nuevo mesociclo antes del cierre.' : 'Calcular nueva pauta de macros y calorías.'}
                        </p>
                      </div>
                    </div>

                    <button
                      onClick={() => {
                        toast.success(`Abriendo editor para ${task.athleteName}...`, { icon: '🚀' });
                        navigate(task.actionRoute || '/lab');
                      }}
                      className="w-full py-2.5 px-3 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-black font-montserrat flex items-center justify-center gap-1.5 shadow-xs transition-all active:scale-95"
                    >
                      <span>{task.cycleType === 'WORKOUT_CYCLE' ? 'Diseñar Próximo Mesociclo' : 'Actualizar Pauta NaaS'}</span>
                      <ArrowRight size={13} />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* LISTA COMPLETA DE TAREAS */}
          <div className="space-y-3">
            <div className="flex items-center justify-between px-1">
              <span className="text-xs font-black font-montserrat uppercase tracking-wider text-slate-400">
                Tus Tareas y Pendientes del Coach
              </span>
              <span className="text-xs text-emerald-600 dark:text-emerald-400 font-bold font-mono">
                {stats.completedTasksCount} / {tasks.length} completadas
              </span>
            </div>

            <div className="space-y-2">
              {filteredTasks.length === 0 ? (
                <div className="py-10 px-6 rounded-3xl bg-white dark:bg-[#0a0d16] border border-slate-200/80 dark:border-zinc-800 text-center flex flex-col items-center justify-center space-y-2">
                  <div className="w-10 h-10 rounded-2xl bg-emerald-50 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 flex items-center justify-center">
                    <CheckSquare size={20} />
                  </div>
                  <h4 className="text-xs font-bold font-montserrat text-slate-800 dark:text-zinc-200">
                    No tenés tareas pendientes
                  </h4>
                  <p className="text-[11px] text-slate-400 max-w-xs">
                    Tu lista está al día. Creá una nueva tarea para recordar renovaciones o planificaciones.
                  </p>
                </div>
              ) : (
                filteredTasks.map((task) => (
                <div
                  key={task.id}
                  onClick={() => handleToggleTask(task.id)}
                  className={`p-4 rounded-2xl border transition-all cursor-pointer flex items-center justify-between gap-3 ${
                    task.completed
                      ? 'bg-slate-50/50 dark:bg-zinc-900/40 border-slate-200/50 dark:border-zinc-800/50 opacity-60'
                      : task.category === 'CYCLE_RENEWAL'
                        ? 'bg-white dark:bg-[#0a0d16] border-amber-300 dark:border-amber-800/80 shadow-xs'
                        : 'bg-white dark:bg-[#0a0d16] border-slate-200/80 dark:border-zinc-800 shadow-2xs hover:border-indigo-400'
                  }`}
                >
                  <div className="flex items-center gap-3.5">
                    <button
                      className={`w-6 h-6 rounded-lg flex items-center justify-center transition-all ${
                        task.completed
                          ? 'bg-emerald-500 text-white'
                          : 'border-2 border-slate-300 dark:border-zinc-700 hover:border-emerald-500'
                      }`}
                    >
                      {task.completed && <CheckCircle2 size={16} />}
                    </button>

                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className={`text-xs font-bold font-montserrat ${task.completed ? 'line-through text-slate-400' : 'text-slate-900 dark:text-white'}`}>
                          {task.title}
                        </h4>
                        {task.isAutoGenerated && (
                          <span className="text-[8px] font-bold px-1.5 py-0.2 rounded bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-400 uppercase">
                            Aviso 7d
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-2 mt-0.5">
                        <span className="text-[9px] font-bold px-1.5 py-0.2 rounded bg-slate-100 dark:bg-zinc-800 text-slate-500 uppercase">
                          {task.category === 'CYCLE_RENEWAL' ? '⚡ Vencimiento de Ciclo' : task.category}
                        </span>
                        <span className="text-[10px] text-slate-400 font-mono">{task.dueDate}</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center gap-2" onClick={e => e.stopPropagation()}>
                    <span className={`text-[9px] font-black uppercase px-2 py-0.5 rounded-md ${
                      task.priority === 'HIGH'
                        ? 'bg-rose-50 dark:bg-rose-950 text-rose-600'
                        : task.priority === 'MEDIUM'
                          ? 'bg-amber-50 dark:bg-amber-950 text-amber-600'
                          : 'bg-slate-100 dark:bg-zinc-800 text-slate-500'
                    }`}>
                      {task.priority}
                    </span>

                    {task.actionRoute && (
                      <button
                        onClick={() => navigate(task.actionRoute!)}
                        className="p-1.5 rounded-lg bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 hover:scale-105 transition-transform"
                        title="Ir al editor"
                      >
                        <ExternalLink size={13} />
                      </button>
                    )}
                  </div>
                </div>
              ))
              )}
            </div>
          </div>
        </div>
      ) : (
        /* ═══════════════════════════════════════════════════════════════
           PESTAÑA 3: LISTA CRONOLÓGICA DE TURNOS DE HOY
           ═══════════════════════════════════════════════════════════════ */
        <div className="space-y-3">
          <div className="flex items-center justify-between px-1">
            <span className="text-xs font-black font-montserrat uppercase tracking-wider text-slate-400">
              Tus Citas Programadas para Hoy
            </span>
            <span className="text-xs text-slate-400 font-mono">
              Hoy, {new Date().toLocaleDateString('es-ES', { weekday: 'long', day: 'numeric', month: 'long' })}
            </span>
          </div>

          <div className="grid grid-cols-1 gap-3">
            {appointments.length === 0 ? (
              <div className="py-12 px-6 rounded-3xl bg-white dark:bg-[#0a0d16] border border-slate-200/80 dark:border-zinc-800 text-center flex flex-col items-center justify-center space-y-3">
                <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
                  <CalendarDays size={24} />
                </div>
                <div className="space-y-1">
                  <h3 className="text-sm font-black font-montserrat text-slate-900 dark:text-white">
                    No tienes turnos agendados todavía
                  </h3>
                  <p className="text-xs text-slate-400 max-w-sm">
                    Comenzá agregando tu primera sesión de entrenamiento o consulta para organizar tu semana.
                  </p>
                </div>
                <button
                  onClick={() => {
                    setNewApt({
                      athleteName: '',
                      title: 'Entrenamiento 1 a 1',
                      type: 'WORKOUT_1ON1',
                      date: new Date().toISOString().split('T')[0],
                      timeStart: '10:00',
                      timeEnd: '11:00',
                      format: 'IN_PERSON',
                      locationOrLink: 'Gimnasio Central',
                      notes: ''
                    });
                    setIsCreatingCustomService(false);
                    setIsAppointmentModalOpen(true);
                  }}
                  className="py-2 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold font-montserrat flex items-center gap-1.5 shadow-sm active:scale-95 transition-all"
                >
                  <Plus size={14} />
                  <span>+ Agendar Primer Turno</span>
                </button>
              </div>
            ) : (
              appointments.map((apt) => (
              <div
                key={apt.id}
                className="p-5 rounded-3xl bg-white dark:bg-[#0a0d16] border border-slate-200/80 dark:border-zinc-800 shadow-xs hover:border-indigo-400 dark:hover:border-indigo-600 transition-all flex flex-col md:flex-row md:items-center justify-between gap-4"
              >
                <div className="flex items-start gap-4">
                  {/* Badge de Horario */}
                  <div className="p-3 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-200 dark:border-indigo-800 text-center shrink-0 min-w-[75px]">
                    <span className="text-xs font-black font-mono text-indigo-600 dark:text-indigo-300 block">
                      {apt.timeStart}
                    </span>
                    <span className="text-[10px] text-slate-400 font-mono">
                      {apt.timeEnd}
                    </span>
                  </div>

                  {/* Info del Turno */}
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      {renderServiceBadge(apt.type)}

                      <span className="text-[10px] font-bold text-slate-400 flex items-center gap-1">
                        {apt.format === 'IN_PERSON' ? <MapPin size={11} /> : <Video size={11} />}
                        <span>{apt.locationOrLink || 'Presencial'}</span>
                      </span>
                    </div>

                    <h3 className="text-sm font-black font-montserrat text-slate-900 dark:text-white">
                      {apt.title}
                    </h3>

                    <div className="flex items-center gap-2 text-xs text-slate-600 dark:text-zinc-300">
                      <img src={apt.athleteAvatar} alt={apt.athleteName} className="w-5 h-5 rounded-full object-cover" />
                      <span className="font-bold">{apt.athleteName}</span>
                      {apt.notes && <span className="text-slate-400 italic text-[11px]">• {apt.notes}</span>}
                    </div>
                  </div>
                </div>

                {/* Botones de Acción */}
                <div className="flex items-center gap-2 shrink-0">
                  {apt.format === 'GOOGLE_MEET' && apt.locationOrLink && (
                    <a
                      href={apt.locationOrLink}
                      target="_blank"
                      rel="noreferrer"
                      className="py-2 px-3.5 rounded-xl bg-emerald-50 dark:bg-emerald-950 text-emerald-600 dark:text-emerald-400 text-xs font-bold font-montserrat flex items-center gap-1.5 border border-emerald-200 dark:border-emerald-800 hover:bg-emerald-100 transition-colors"
                    >
                      <Video size={13} />
                      <span>Abrir Meet</span>
                    </a>
                  )}

                  <button
                    onClick={() => navigate('/inbox')}
                    className="py-2 px-3.5 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-zinc-800 text-slate-700 dark:text-zinc-200 text-xs font-bold font-montserrat transition-all"
                  >
                    Chat
                  </button>

                  <button
                    onClick={() => {
                      toast.success('Sesión iniciada', { icon: '🚀' });
                      navigate('/lab');
                    }}
                    className="py-2 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold font-montserrat transition-all shadow-xs"
                  >
                    Iniciar Sesión
                  </button>
                </div>
              </div>
            ))
            )}
          </div>
        </div>
      )}

      {/* 🌟 5. MODAL: AGENDAR NUEVO TURNO (CON SERVICIOS PERSONALIZABLES) */}
      <AnimatePresence>
        {isAppointmentModalOpen && (
          <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-3xl max-w-lg w-full p-6 shadow-2xl space-y-4 font-lato"
            >
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-zinc-800 pb-3">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-xl bg-indigo-50 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center font-bold">
                    <CalendarDays size={16} />
                  </div>
                  <h3 className="text-sm font-black font-montserrat text-slate-900 dark:text-white uppercase tracking-wider">
                    Agendar Nuevo Turno
                  </h3>
                </div>
                <button onClick={() => setIsAppointmentModalOpen(false)} className="text-slate-400 hover:text-slate-600">
                  <X size={18} />
                </button>
              </div>

              <form onSubmit={handleCreateAppointment} className="space-y-3">
                <div>
                  <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Nombre del Atleta o Paciente</label>
                  <input
                    type="text"
                    required
                    placeholder="Ej: Nahuel Dangelo"
                    value={newApt.athleteName}
                    onChange={e => setNewApt({ ...newApt, athleteName: e.target.value })}
                    className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="text-[10px] font-black uppercase text-slate-400 block">Tipo de Servicio</label>
                      <button
                        type="button"
                        onClick={() => setIsCreatingCustomService(true)}
                        className="text-[10px] font-bold text-indigo-600 dark:text-indigo-400 hover:underline flex items-center gap-0.5"
                      >
                        <PlusCircle size={10} /> + Otro
                      </button>
                    </div>

                    <select
                      value={newApt.type}
                      onChange={e => handleServiceTypeChange(e.target.value)}
                      className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white font-medium"
                    >
                      {serviceTypes.map(s => (
                        <option key={s.id} value={s.id}>
                          {s.name}
                        </option>
                      ))}
                      <option value="CREATE_CUSTOM">✨ + Agregar otro servicio personalizado...</option>
                    </select>
                  </div>

                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Modalidad</label>
                    <select
                      value={newApt.format}
                      onChange={e => setNewApt({ ...newApt, format: e.target.value as any })}
                      className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                    >
                      <option value="IN_PERSON">📍 Presencial (Consultorio / Gym)</option>
                      <option value="GOOGLE_MEET">💻 Google Meet</option>
                      <option value="WHATSAPP">📱 WhatsApp Call</option>
                    </select>
                  </div>
                </div>

                {/* Sub-formulario animado: Crear Servicio Personalizado */}
                <AnimatePresence>
                  {isCreatingCustomService && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="p-3 rounded-2xl bg-indigo-50/70 dark:bg-indigo-950/40 border border-indigo-200 dark:border-indigo-800 space-y-2"
                    >
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] font-black uppercase tracking-wider text-indigo-700 dark:text-indigo-300 flex items-center gap-1">
                          <Tag size={11} /> Nuevo Tipo de Servicio
                        </span>
                        <button
                          type="button"
                          onClick={() => setIsCreatingCustomService(false)}
                          className="text-slate-400 hover:text-slate-600 text-xs"
                        >
                          <X size={14} />
                        </button>
                      </div>

                      <div className="flex gap-2">
                        <div className="flex gap-1 items-center bg-white dark:bg-zinc-800 rounded-xl px-2 border border-slate-200 dark:border-zinc-700">
                          <select
                            value={customServiceEmoji}
                            onChange={e => setCustomServiceEmoji(e.target.value)}
                            className="bg-transparent text-sm outline-none cursor-pointer"
                          >
                            {EMOJI_OPTIONS.map(em => (
                              <option key={em} value={em}>{em}</option>
                            ))}
                          </select>
                        </div>

                        <input
                          type="text"
                          placeholder="Ej: Masaje Deportivo, Fisioterapia, Coaching Mental..."
                          value={customServiceName}
                          onChange={e => setCustomServiceName(e.target.value)}
                          className="flex-1 px-3 py-1.5 rounded-xl text-xs bg-white dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                        />

                        <button
                          type="button"
                          onClick={handleSaveCustomService}
                          className="px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold font-montserrat shadow-xs flex items-center gap-1"
                        >
                          <Check size={12} /> Guardar
                        </button>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>

                <div>
                  <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Título o Motivo de la Cita</label>
                  <input
                    type="text"
                    placeholder="Ej: Medición Antropométrica de 6 pliegues o Sesión 1 a 1"
                    value={newApt.title}
                    onChange={e => setNewApt({ ...newApt, title: e.target.value })}
                    className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                  />
                </div>

                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Fecha</label>
                    <input
                      type="date"
                      value={newApt.date}
                      onChange={e => setNewApt({ ...newApt, date: e.target.value })}
                      className="w-full px-3 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                    />
                  </div>

                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Hora Inicio</label>
                    <input
                      type="time"
                      value={newApt.timeStart}
                      onChange={e => setNewApt({ ...newApt, timeStart: e.target.value })}
                      className="w-full px-3 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white font-mono"
                    />
                  </div>

                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Hora Fin</label>
                    <input
                      type="time"
                      value={newApt.timeEnd}
                      onChange={e => setNewApt({ ...newApt, timeEnd: e.target.value })}
                      className="w-full px-3 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white font-mono"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Ubicación o Enlace de Meet</label>
                  <input
                    type="text"
                    placeholder="Ej: Consultorio 2 o https://meet.google.com/..."
                    value={newApt.locationOrLink}
                    onChange={e => setNewApt({ ...newApt, locationOrLink: e.target.value })}
                    className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                  />
                </div>

                <div className="flex justify-end gap-2 pt-3">
                  <button
                    type="button"
                    onClick={() => setIsAppointmentModalOpen(false)}
                    className="py-2 px-4 rounded-xl bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-zinc-300 text-xs font-bold"
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    className="py-2 px-5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold font-montserrat shadow-xs"
                  >
                    Guardar Turno
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* 🌟 6. MODAL: NUEVA TAREA */}
      <AnimatePresence>
        {isTaskModalOpen && (
          <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-3xl max-w-md w-full p-6 shadow-2xl space-y-4 font-lato"
            >
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-zinc-800 pb-3">
                <div className="flex items-center gap-2">
                  <CheckSquare size={16} className="text-emerald-500" />
                  <h3 className="text-sm font-black font-montserrat text-slate-900 dark:text-white uppercase tracking-wider">
                    Nueva Tarea / Pendiente
                  </h3>
                </div>
                <button onClick={() => setIsTaskModalOpen(false)} className="text-slate-400 hover:text-slate-600">
                  <X size={18} />
                </button>
              </div>

              <form onSubmit={handleCreateTask} className="space-y-3">
                <div>
                  <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">¿Qué tienes que hacer?</label>
                  <input
                    type="text"
                    required
                    placeholder="Ej: Armar rutina para Javier D."
                    value={newTaskTitle}
                    onChange={e => setNewTaskTitle(e.target.value)}
                    className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                  />
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Categoría</label>
                    <select
                      value={newTaskCategory}
                      onChange={e => setNewTaskCategory(e.target.value as any)}
                      className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                    >
                      <option value="PLAN">📋 Planificación</option>
                      <option value="VALIDATION">📹 Validación</option>
                      <option value="CLIENT">👥 Cliente</option>
                      <option value="ADMIN">⚙️ Administración</option>
                    </select>
                  </div>

                  <div>
                    <label className="text-[10px] font-black uppercase text-slate-400 block mb-1">Prioridad</label>
                    <select
                      value={newTaskPriority}
                      onChange={e => setNewTaskPriority(e.target.value as any)}
                      className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                    >
                      <option value="HIGH">🔴 Alta</option>
                      <option value="MEDIUM">🟡 Media</option>
                      <option value="LOW">🟢 Baja</option>
                    </select>
                  </div>
                </div>

                <div className="flex justify-end gap-2 pt-3">
                  <button
                    type="button"
                    onClick={() => setIsTaskModalOpen(false)}
                    className="py-2 px-4 rounded-xl bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-zinc-300 text-xs font-bold"
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    className="py-2 px-5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold font-montserrat shadow-xs"
                  >
                    Agregar Tarea
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* 🌟 7. MODAL: CONFIGURAR ALERTAS DE CICLO */}
      <AnimatePresence>
        {isCycleConfigModalOpen && (
          <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-xs flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-3xl max-w-md w-full p-6 shadow-2xl space-y-4 font-lato"
            >
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-zinc-800 pb-3">
                <div className="flex items-center gap-2">
                  <BellRing size={16} className="text-amber-500" />
                  <h3 className="text-sm font-black font-montserrat text-slate-900 dark:text-white uppercase tracking-wider">
                    Alertas Automáticas de Fin de Ciclo
                  </h3>
                </div>
                <button onClick={() => setIsCycleConfigModalOpen(false)} className="text-slate-400 hover:text-slate-600">
                  <X size={18} />
                </button>
              </div>

              <div className="space-y-3 text-xs text-slate-600 dark:text-zinc-300">
                <p>
                  El sistema revisa automáticamente la duración de las rutinas y dietas de tus atletas.
                </p>

                <div className="p-3 rounded-2xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800/80 space-y-1 text-amber-900 dark:text-amber-300">
                  <span className="font-bold flex items-center gap-1.5">
                    <Hourglass size={13} /> Regla Activa: 7 Días de Anticipación
                  </span>
                  <p className="text-[11px] leading-relaxed">
                    Cuando a un atleta le queden 7 días o menos para terminar su plan, aparecerá una tarea automática con un botón directo para preparar el siguiente ciclo.
                  </p>
                </div>

                <div className="space-y-2 pt-2">
                  <label className="text-[10px] font-black uppercase text-slate-400 block">Anticipación de Alerta</label>
                  <select
                    defaultValue="7"
                    className="w-full px-3.5 py-2 rounded-xl text-xs bg-slate-50 dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 outline-none text-slate-900 dark:text-white"
                  >
                    <option value="7">⚡ 1 Semana antes (7 días) — Recomendado</option>
                    <option value="10">⚡ 10 días antes</option>
                    <option value="5">⚡ 5 días antes</option>
                    <option value="3">⚡ 3 días antes</option>
                  </select>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-3">
                <button
                  onClick={() => {
                    setIsCycleConfigModalOpen(false);
                    toast.success('Configuración de alertas guardada', { icon: '⚙️' });
                  }}
                  className="py-2 px-5 rounded-xl bg-amber-500 hover:bg-amber-400 text-slate-950 text-xs font-black font-montserrat shadow-xs"
                >
                  Guardar Cambios
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

    </div>
  );
};
